"""Pretender — a light MaiBot.

Public re-exports for plugin authors: the boundary types, the error
taxonomy, the config root, and the extension Protocols. Everything else is
imported from its own module.
"""

from __future__ import annotations

__version__ = "0.1.0"

from pretender.app import LearnerScheduler, SemanticBackfill
from pretender.budget import (
    BudgetBlockedError,
    BudgetDecision,
    BudgetManager,
    BudgetUsage,
    BudgetedClient,
    LearnerBudget,
)
from pretender.config import AgentConfig, Config, LearnConfig, LearnProfile, MediaConfig, RuntimeOverlay
from pretender.cycle import (
    AdaptiveContext,
    AdaptiveContextService,
    AgentOutcome,
    CycleRunner,
    PhaseAgent,
    ReplayResult,
    assemble_snapshot,
    replay_corpus,
    replay_marker_schedule,
    sweep_marker_schedule,
)
from pretender.doctor import Doctor, DoctorReport, ProbeResult
from pretender.emoji import (
    VisionResult,
    normalize_description,
    parse_vision_result,
    scrub_description,
    validate_asset_id,
    validate_candidate,
    validate_catalog_key,
    validate_sha256,
)
from pretender.embed import EmbeddingCache, EmbeddingResult, OptionalEmbeddingService
from pretender.errors import (
    AdapterError,
    ClaimError,
    ConfigError,
    LLMError,
    LLMPermanentError,
    LLMTransientError,
    PermanentError,
    PretenderError,
    PromptError,
    RegistryError,
    RepoError,
    ToolError,
    TransientError,
)
from pretender.person import MAX_ALIASES, ObserveResult, PersonService, ProfileResult
from pretender.planner import PlanIntent, PlanResult, Planner
from pretender.replyer import ReplyDraft, Replyer
from pretender.search import MemoryRecallHit, MemorySearch, normalize_query, rrf_merge
from pretender.registry import (
    HookBus,
    PluginAPI,
    PluginManifest,
    PluginLoadResult,
    PluginLoader,
    PluginRegistry,
    StagingRegistry,
    configured_plugin_manifest,
    feature_implementation_fingerprint,
)
from pretender.seams import (
    Adapter,
    AdaptiveRepository,
    BudgetStore,
    ChatControlRepository,
    Clock,
    CycleEndHook,
    Embedder,
    EventHook,
    GateContext,
    GateFeature,
    KnowledgeRepository,
    LearnerDef,
    LLMClient,
    MediaRepository,
    OutputStage,
    Plugin,
    PreSendHook,
    Repository,
)
from pretender.types import (
    AdapterEvent,
    AdapterSpec,
    AgentAdaptiveContext,
    BackoffFacts,
    ChatControl,
    ChatControlIntent,
    ChatControlKind,
    ChatIdentity,
    ChatKey,
    ChatState,
    ClaimBusy,
    ClaimGrant,
    CommitSeq,
    Contribution,
    CorpusMarker,
    CycleClaim,
    CycleFinish,
    CycleId,
    Decision,
    DecisionTrace,
    DispatchCause,
    DispatchDeferred,
    DispatchGrant,
    DispatchId,
    DispatchRequest,
    DispatchSettle,
    EchoStatus,
    EmbeddingGeneration,
    EventId,
    GateSnapshot,
    IngestResult,
    LearnerBatch,
    LearnerBusy,
    LearnerDraft,
    LearnerGrant,
    LearnerRun,
    LearnerRunRequest,
    LearnerSpec,
    LearnerState,
    LexicalHit,
    LLMResponse,
    MediaAsset,
    MediaAssetCandidate,
    MediaKind,
    MediaSafetyStatus,
    MemoryRecord,
    MemorySourceBatch,
    MemoryWriteRequest,
    Message,
    MessageId,
    MessageRowId,
    Outgoing,
    OutboxItem,
    PersonKey,
    PersonProfile,
    PlatformId,
    Reason,
    RecentSnapshot,
    Record,
    RecordHit,
    RuntimeMode,
    Segment,
    SelfId,
    SenderId,
    SettlementNotice,
    ToolCall,
    ToolCallId,
    ToolResult,
    TranscriptMessage,
    VectorRow,
    WakeKind,
)
from pretender.tools import ToolRegistry, ToolSpec, tool
from pretender.tools.chatctl import (
    CHATCTL_TOOL_NAMES,
    ChatControlCallbacks,
    notify_chat,
    set_focus,
)
from pretender.tools.knowledge import (
    KNOWLEDGE_TOOL_NAMES,
    MAX_JARGON_CHARS,
    MAX_JARGON_HITS,
    KnowledgeCallbacks,
    query_jargon,
    query_memory,
    query_person_profile,
)
from pretender.tools.media import (
    MEDIA_TOOL_NAMES,
    MediaCallbacks,
    MediaReplyIntent,
    catalog_prompt,
    media_segment_for_intent,
    send_emoji,
    send_image,
)
from pretender.toolparse import (
    NO_ACTION_NAME,
    parse_tool_calls,
    tolerant_loads,
    validate_arguments,
)
from pretender.vectors import (
    VectorCache,
    VectorHit,
    VectorIndex,
    blob_to_ndarray,
    cosine_top_k,
    ndarray_to_blob,
    normalize,
)
from pretender.llm import OpenAIClient
from pretender.media import MediaHarvester, MediaResolvingAdapter, MediaRevoker, MediaStore
from pretender.learn import (
    BEHAVIOR_MAX,
    BEHAVIOR_SPEC,
    DEFAULT_LEARN_DEADLINE_S,
    DEFAULT_LEARN_FAILURE_BACKOFF_CAP_S,
    DEFAULT_LEARN_LEASE_S,
    EFFECT_BANDS,
    EFFECT_CATEGORIZATIONS,
    EFFECT_SPEC,
    EXPRESSION_FIELD_MAX,
    EXPRESSION_MAX,
    EXPRESSION_SPEC,
    IMPRESSION_FIELD_MAX,
    IMPRESSION_MAX,
    IMPRESSION_SPEC,
    JARGON_MAX,
    JARGON_SPEC,
    LEARN_PROFILE,
    LEARNING_TYPES,
    SPECS,
    SUMMARY_CUES_MAX,
    SUMMARY_CUES_MIN,
    SUMMARY_SPEC,
    VALIDATORS,
    ACTOR_TYPES,
    LearnerParseError,
    LearnerPipeline,
    LearnerRunResult,
    LearnerValidationError,
    canonical_content,
    derive_effect_delta,
    escape_untrusted,
    parse_json_response,
    render_attributed_batch,
    render_batch,
    render_records,
    select_records,
    source_hash,
)
from pretender.memory import (
    DEFAULT_SOURCE_TAIL,
    MemoryService,
    SummarizeResult,
    default_capsule_summarizer,
)
from pretender.output import (
    OutputPipeline,
    SanitizeStage,
    SplitStage,
    TypoStage,
    detect_protected_spans,
    load_frequency,
    sanitize_text,
    split_text,
    stable_group_id,
    typo_text,
)

__all__ = [
    "__version__",
    # config
    "AgentConfig",
    "Config",
    "LearnConfig",
    "LearnProfile",
    "MediaConfig",
    "RuntimeOverlay",
    # cycle lane
    "AdaptiveContext",
    "AdaptiveContextService",
    "AgentOutcome",
    "CycleRunner",
    "PhaseAgent",
    "ReplayResult",
    "assemble_snapshot",
    "replay_corpus",
    "replay_marker_schedule",
    "sweep_marker_schedule",
    # doctor
    "Doctor",
    "DoctorReport",
    "ProbeResult",
    # media catalog validation (Phase 6 P6.5)
    "validate_candidate",
    "validate_catalog_key",
    "validate_sha256",
    "validate_asset_id",
    "scrub_description",
    "normalize_description",
    "VisionResult",
    "parse_vision_result",
    # media runtime (Phase 6 P6.5b)
    "MediaHarvester",
    "MediaRevoker",
    "MediaResolvingAdapter",
    "MediaStore",
    "MEDIA_TOOL_NAMES",
    "MediaCallbacks",
    "MediaReplyIntent",
    "catalog_prompt",
    "media_segment_for_intent",
    "send_emoji",
    "send_image",
    # semantic runtime (Gate 5)
    "SemanticBackfill",
    # learner worker (Phase 6 P6.4)
    "LearnerScheduler",
    # retrieval core (Phase 5)
    "OptionalEmbeddingService",
    "EmbeddingResult",
    "EmbeddingCache",
    "VectorIndex",
    "VectorCache",
    "VectorHit",
    "ndarray_to_blob",
    "blob_to_ndarray",
    "normalize",
    "cosine_top_k",
    "MemorySearch",
    "MemoryRecallHit",
    "normalize_query",
    "rrf_merge",
    # person service (Phase 5 knowledge lane)
    "MAX_ALIASES",
    "ObserveResult",
    "PersonService",
    "ProfileResult",
    # durable memory service (Phase 5 knowledge lane)
    "DEFAULT_SOURCE_TAIL",
    "MemoryService",
    "SummarizeResult",
    "default_capsule_summarizer",
    # knowledge tools (Phase 5 retrieval surface)
    "KNOWLEDGE_TOOL_NAMES",
    "KnowledgeCallbacks",
    "query_memory",
    "query_person_profile",
    "query_jargon",
    "MAX_JARGON_CHARS",
    "MAX_JARGON_HITS",
    # planner / replyer / budget (Phase 3 agent lane)
    "PlanIntent",
    "PlanResult",
    "Planner",
    "ReplyDraft",
    "Replyer",
    "BudgetDecision",
    "BudgetManager",
    "BudgetUsage",
    "BudgetedClient",
    "BudgetBlockedError",
    "LearnerBudget",
    # errors
    "AdapterError",
    "ClaimError",
    "ConfigError",
    "PermanentError",
    "PretenderError",
    "PromptError",
    "RegistryError",
    "RepoError",
    "ToolError",
    "TransientError",
    "LLMError",
    "LLMPermanentError",
    "LLMTransientError",
    # seams
    "Adapter",
    "AdaptiveRepository",
    "BudgetStore",
    "ChatControlRepository",
    "Clock",
    "CycleEndHook",
    "Embedder",
    "EventHook",
    "GateContext",
    "GateFeature",
    "KnowledgeRepository",
    "LearnerDef",
    "LLMClient",
    "MediaRepository",
    "OutputStage",
    "Plugin",
    "PreSendHook",
    "Repository",
    # registry
    "HookBus",
    "PluginAPI",
    "PluginLoadResult",
    "PluginLoader",
    "PluginRegistry",
    "StagingRegistry",
    # types
    "AdapterEvent",
    "AgentAdaptiveContext",
    "BackoffFacts",
    "ChatControl",
    "ChatControlIntent",
    "ChatControlKind",
    "ChatIdentity",
    "ChatKey",
    "ChatState",
    "ClaimBusy",
    "ClaimGrant",
    "CommitSeq",
    "Contribution",
    "CorpusMarker",
    "CycleClaim",
    "CycleFinish",
    "CycleId",
    "Decision",
    "DecisionTrace",
    "DispatchCause",
    "DispatchDeferred",
    "DispatchGrant",
    "DispatchId",
    "DispatchRequest",
    "DispatchSettle",
    "EchoStatus",
    "EmbeddingGeneration",
    "EventId",
    "GateSnapshot",
    "IngestResult",
    "LearnerBatch",
    "LearnerBusy",
    "LearnerDraft",
    "LearnerGrant",
    "LearnerRun",
    "LearnerRunRequest",
    "LearnerSpec",
    "LearnerState",
    "LexicalHit",
    "LLMResponse",
    "MediaAsset",
    "MediaAssetCandidate",
    "MediaKind",
    "MediaSafetyStatus",
    "MemoryRecord",
    "MemorySourceBatch",
    "MemoryWriteRequest",
    "Message",
    "MessageId",
    "MessageRowId",
    "Outgoing",
    "OutboxItem",
    "PersonKey",
    "PersonProfile",
    "PlatformId",
    "Reason",
    "RecentSnapshot",
    "Record",
    "RecordHit",
    "RuntimeMode",
    "Segment",
    "SelfId",
    "SenderId",
    "SettlementNotice",
    "ToolCall",
    "ToolCallId",
    "ToolResult",
    "TranscriptMessage",
    "VectorRow",
    "WakeKind",
    # tools
    "ToolRegistry",
    "ToolSpec",
    "tool",
    # chat-control tools (Phase 6 P6.6b)
    "CHATCTL_TOOL_NAMES",
    "ChatControlCallbacks",
    "set_focus",
    "notify_chat",
    # tool parsing
    "NO_ACTION_NAME",
    "parse_tool_calls",
    "tolerant_loads",
    "validate_arguments",
    # llm
    "OpenAIClient",
    # learner lane (Phase 6)
    "LearnerPipeline",
    "LearnerRunResult",
    "LEARN_PROFILE",
    "DEFAULT_LEARN_DEADLINE_S",
    "DEFAULT_LEARN_FAILURE_BACKOFF_CAP_S",
    "DEFAULT_LEARN_LEASE_S",
    "EXPRESSION_SPEC",
    "BEHAVIOR_SPEC",
    "JARGON_SPEC",
    "SUMMARY_SPEC",
    "EFFECT_SPEC",
    "IMPRESSION_FIELD_MAX",
    "IMPRESSION_MAX",
    "IMPRESSION_SPEC",
    "SPECS",
    "VALIDATORS",
    "ACTOR_TYPES",
    "LEARNING_TYPES",
    "EXPRESSION_MAX",
    "EXPRESSION_FIELD_MAX",
    "BEHAVIOR_MAX",
    "JARGON_MAX",
    "SUMMARY_CUES_MIN",
    "SUMMARY_CUES_MAX",
    "EFFECT_CATEGORIZATIONS",
    "EFFECT_BANDS",
    "derive_effect_delta",
    "LearnerParseError",
    "LearnerValidationError",
    "parse_json_response",
    "escape_untrusted",
    "render_attributed_batch",
    "render_batch",
    "render_records",
    "select_records",
    "source_hash",
    "canonical_content",
    # output pipeline
    "OutputPipeline",
    "SanitizeStage",
    "SplitStage",
    "TypoStage",
    "detect_protected_spans",
    "sanitize_text",
    "split_text",
    "typo_text",
    "load_frequency",
    "stable_group_id",
]
