#!/usr/bin/env python3
"""Small, deliberately boring, one-click deployment wizard.

The wizard only uses the Python standard library.  In particular, commands are
always passed to ``subprocess`` as argument arrays: no shell is involved.
"""

from __future__ import annotations

import argparse
import getpass
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from typing import Any, Callable, Mapping, Protocol, Sequence
from urllib.parse import urlsplit

try:
    import fcntl
except ImportError:  # pragma: no cover - native locking is Linux-oriented
    fcntl = None  # type: ignore[assignment]

try:  # tomllib is 3.11+; the wizard still runs on the 3.9/3.10 system Python
    import tomllib
except ImportError:  # pragma: no cover - exercised only on older interpreters
    tomllib = None  # type: ignore[assignment]


DEFAULT_IMAGE = "ghcr.io/redstonexs/pretender:v1.0.2"
LLM_ENV = "PRETENDER_LLM_API_KEY"
ONEBOT_ENV = "ONEBOT_ACCESS_TOKEN"
WIZARD_MARKER = "Generated by the Pretender deployment wizard."
_MODEL_MAX = 200
_ENV_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SECRET_CHARS = re.compile(r"^[A-Za-z0-9._\-/+=:@%]+$")
_IMAGE_TAG = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$")
_IMAGE_DIGEST = re.compile(r"^[A-Za-z][A-Za-z0-9+._-]*:[0-9A-Fa-f]{32,}$")
_IMAGE_REFERENCE = re.compile(r"^[A-Za-z0-9._/@:+-]+$")
WIZARD_LOCK_CONTAINER = "pretender-wizard-lock"
WIZARD_LOCK_LABEL = "io.pretender.wizard-lock=true"
DEFAULT_PORT = 3002
#: The generated ``[bot]`` / ``[gate]`` values. These MUST be written into the
#: config even though they equal (or are close to) the dataclass defaults: a
#: generated file with no gate section gives the operator nothing to turn, and
#: "I cannot find any switch to let it talk" is the result.
DEFAULT_BOT_NAME = "麦麦"
DEFAULT_GATE_THRESHOLD = 8
#: Below the dataclass default of 80. At 80 an unaddressed group message can
#: reach at most ~66, so the bot is structurally @-only and never joins a
#: conversation on its own.
DEFAULT_GATE_TRIGGER_SCORE = 60
#: How many ports above the preferred one are probed before giving up.
PORT_SCAN_SPAN = 40
DEFAULT_ONEBOT_PATH = "/onebot/v11/ws"


# ── messages ────────────────────────────────────────────────────────────────
# The wizard is used mostly by Chinese-speaking NapCat operators, so zh-CN is
# the default and English is a flag away.  Every user-visible string lives
# here: a missing key falls back to English and then to the key itself.

MESSAGES: dict[str, dict[str, str]] = {
    "zh": {
        "prompt.target": "部署方式：1) Docker Compose（推荐） 2) docker run 3) 本机原生",
        "prompt.native_mode": "本机运行方式：f) 前台运行（默认） s) systemd 用户服务",
        "prompt.provider": "模型提供商：1) DeepSeek 2) OpenAI 3) 自定义 OpenAI 兼容接口",
        "prompt.base_url": "OpenAI 兼容 base URL",
        "prompt.planner_model": "模型 ID",
        "prompt.reply_model": "回复模型 ID（留空与上面相同）",
        "prompt.api_key": "API key（输入不回显）：",
        "prompt.onebot_token": "OneBot token（留空自动生成；输入不回显）：",
        "prompt.port": "OneBot 反向 WebSocket 端口",
        "prompt.splitting": "启用消息分段",
        "prompt.typo": "启用错别字模拟",
        "prompt.media": "启用媒体库",
        "prompt.image": "容器镜像",
        "prompt.http_loopback": "这是本机回环上的明文 HTTP，确认允许",
        "prompt.default": "默认",
        "prompt.setup_gate": "按上述方案写入配置并安装（此步不会启动机器人）",
        "prompt.start_gate": "现在启动机器人（live）",
        "port.busy": "端口 {port} 已被占用{holder}，改用 {chosen}。",
        "port.holder": "（占用者：{holder}）",
        "summary.title": "部署方案（密钥已隐藏）：",
        "summary.target": "部署方式",
        "summary.provider": "提供商",
        "summary.planner": "规划模型",
        "summary.reply": "回复模型",
        "summary.api_key": "API key",
        "summary.token": "OneBot token",
        "summary.redacted": "<已隐藏>",
        "summary.features": "功能开关",
        "summary.config": "配置文件",
        "summary.storage": "数据库",
        "summary.image": "镜像",
        "summary.service": "运行方式",
        "summary.port": "OneBot 端口",
        "msg.cancelled": "已取消。",
        "msg.dry_run": "演练模式：未写入任何文件，也未执行任何命令。",
        "msg.setup_done": "配置已写入，安装完成。",
        "msg.napcat_title": "下一步：在 NapCat 中配置反向 WebSocket 客户端",
        "msg.napcat_url": "  连接地址：{url}",
        "msg.napcat_token": "  访问令牌：与 {path} 中的 {env} 完全一致",
        "msg.napcat_token_cmd": "  查看令牌：{command}",
        "msg.napcat_docker": "如果 NapCat 运行在 Docker 中：Linux 原生 host 网络是必需的，因为 Pretender 的 reverse_ws 只绑定回环地址；不要添加 ports: 映射。保留 NapCat 的 /app/.config/QQ 和 /app/napcat/config 挂载。不要自动修改 NapCat 的外部配置。",
        "msg.napcat_login": "连接地址必须保留 message_format=array。重启后可能需要重新扫码登录；仅设置 ACCOUNT 不会启用无人值守重启。无人值守凭据只能放在 NapCat 自己受保护的 secret 配置中。",
        "msg.napcat_wait": "在 NapCat 连接配置保存并生效后，再继续下一步。",
        "msg.not_started": "安装完成，尚未启动。稍后执行：{command}",
        "msg.started": "已启动。",
        "msg.manage": "常用命令：",
        "msg.systemd_linger": "已启用 systemd 用户服务；未自动开启 linger（注销后服务会停止，如需常驻请执行 loginctl enable-linger）。",
        "error.prefix": "部署失败：{error}",
        "error.port": "端口必须是 1024-65535 之间的整数",
        "error.no_free_port": "{host} 上 {port} 起的 {span} 个端口都被占用；请手动指定一个空闲端口",
        "error.listener": "{host}:{port} 已被占用{holder}；请换一个端口（--port）或停止占用进程",
        "error.api_key_env": "非交互模式需要通过环境变量 {env} 提供 API key",
    },
    "en": {
        "prompt.target": "Deployment target: 1) Docker Compose (recommended), 2) docker run, 3) native host",
        "prompt.native_mode": "Native mode: f) foreground (default), s) systemd user service",
        "prompt.provider": "Provider: 1) DeepSeek, 2) OpenAI, 3) custom OpenAI-compatible",
        "prompt.base_url": "OpenAI-compatible base URL",
        "prompt.planner_model": "Model ID",
        "prompt.reply_model": "Reply model ID (blank reuses the one above)",
        "prompt.api_key": "API key (input hidden): ",
        "prompt.onebot_token": "OneBot token (blank generates one; input hidden): ",
        "prompt.port": "OneBot reverse WebSocket port",
        "prompt.splitting": "Enable message splitting",
        "prompt.typo": "Enable typo simulation",
        "prompt.media": "Enable media catalog",
        "prompt.image": "Container image",
        "prompt.http_loopback": "This is plain HTTP on loopback; explicitly allow it",
        "prompt.default": "default",
        "prompt.setup_gate": "Set up this plan now (no live process yet)",
        "prompt.start_gate": "Start the live process now",
        "port.busy": "Port {port} is already in use{holder}; using {chosen} instead.",
        "port.holder": " (held by {holder})",
        "summary.title": "Deployment plan (secrets redacted):",
        "summary.target": "target",
        "summary.provider": "provider",
        "summary.planner": "planner model",
        "summary.reply": "reply model",
        "summary.api_key": "API key",
        "summary.token": "OneBot token",
        "summary.redacted": "<redacted>",
        "summary.features": "features",
        "summary.config": "config",
        "summary.storage": "storage",
        "summary.image": "image",
        "summary.service": "service",
        "summary.port": "OneBot port",
        "msg.cancelled": "Cancelled.",
        "msg.dry_run": "Dry run: no files were written and no commands were run.",
        "msg.setup_done": "Configuration written; setup complete.",
        "msg.napcat_title": "Next: configure the reverse WebSocket client in NapCat",
        "msg.napcat_url": "  URL:   {url}",
        "msg.napcat_token": "  Token: exactly the {env} value in {path}",
        "msg.napcat_token_cmd": "  Read it with: {command}",
        "msg.napcat_docker": "If NapCat is Dockerized: native Linux host networking is required because Pretender reverse_ws binds only to loopback; do not add a ports: mapping. Preserve NapCat's /app/.config/QQ and /app/napcat/config mounts. Do not modify NapCat's external configuration automatically.",
        "msg.napcat_login": "Keep message_format=array in the connection URL. QR login may be required after a restart; setting ACCOUNT alone does not enable unattended restart. Unattended credentials belong only in NapCat's own protected secret configuration.",
        "msg.napcat_wait": "Continue only after NapCat has saved that connection.",
        "msg.not_started": "Setup complete; live process was not started. Start it later with: {command}",
        "msg.started": "Started.",
        "msg.manage": "Useful commands:",
        "msg.systemd_linger": "Systemd user service enabled; linger was not enabled automatically.",
        "error.prefix": "Deployment failed: {error}",
        "error.port": "port must be an integer between 1024 and 65535",
        "error.no_free_port": "{span} ports from {port} up are all busy on {host}; pick a free port explicitly",
        "error.listener": "{host}:{port} is already in use{holder}; choose another port (--port) or stop that process",
        "error.api_key_env": "non-interactive mode needs the API key in the {env} environment variable",
    },
}

_LANGUAGE = "zh"


def detect_language(environ: Mapping[str, str] | None = None) -> str:
    """Pick zh for Chinese locales, English otherwise; never raise."""

    environ = os.environ if environ is None else environ
    for name in ("PRETENDER_LANG", "LC_ALL", "LC_MESSAGES", "LANG"):
        value = environ.get(name, "")
        if not value:
            continue
        lowered = value.lower()
        if lowered.startswith("zh") or "zh_" in lowered:
            return "zh"
        if lowered in {"c", "posix"}:
            continue
        return "en"
    return "zh"


def set_language(language: str) -> str:
    """Set the wizard language; ``auto`` resolves from the environment."""

    global _LANGUAGE
    if language == "auto":
        language = detect_language()
    if language not in MESSAGES:
        raise DeployError(f"unsupported language {language!r}")
    _LANGUAGE = language
    return _LANGUAGE


def t(key: str, **values: Any) -> str:
    """Look up a message, falling back to English and then to the key."""

    template = MESSAGES.get(_LANGUAGE, {}).get(key) or MESSAGES["en"].get(key) or key
    if not values:
        return template
    try:
        return template.format(**values)
    except (KeyError, IndexError):
        return template


class DeployError(RuntimeError):
    """An expected, user-actionable deployment error."""


@dataclass(frozen=True)
class Provider:
    base_url: str
    planner_model: str
    reply_model: str
    api_key: str
    http_loopback_confirmed: bool = False
    #: A model on the SAME base_url that accepts image input, or "" when the
    #: provider serves none. Vision is a separate capability from chat: on
    #: opencode.ai/zen, ``ling-3.0-flash-fin-free`` answers text fine and
    #: rejects images with "No endpoints found that support image input",
    #: while ``hy3-free`` accepts them.
    vision_model: str = ""
    #: An embedding model, or "" when the provider has no /embeddings
    #: endpoint at all. Without it, memory recall and expression selection
    #: fall back to FTS and record weight.
    embed_model: str = ""


@dataclass(frozen=True)
class Features:
    splitting: bool = True
    typo: bool = True
    media_enabled: bool = False
    #: The adaptive learners (expression / behavior / jargon / summary /
    #: effect). Off in the dataclass default so an empty TOML boots a bare
    #: bot; ON here, because a deployment without them has a frozen reply
    #: style and never learns how its group actually talks.
    learning: bool = True


@dataclass(frozen=True)
class DeploymentPlan:
    target: str
    provider: Provider
    features: Features
    onebot_token: str
    project_root: Path
    config_path: Path
    environment_path: Path
    storage_path: str
    image: str = DEFAULT_IMAGE
    native_service: str = "foreground"
    home: Path = Path.home()
    port: int = DEFAULT_PORT

    @property
    def onebot_url(self) -> str:
        """The exact reverse-WebSocket URL NapCat has to dial."""

        return f"ws://127.0.0.1:{self.port}{DEFAULT_ONEBOT_PATH}?message_format=array"

    @property
    def venv_path(self) -> Path:
        return self.home / ".local" / "share" / "pretender" / "venv"

    @property
    def unit_path(self) -> Path:
        return self.home / ".config" / "systemd" / "user" / "pretender.service"

    @property
    def venv_marker_path(self) -> Path:
        return self.venv_path.parent / "venv.wizard.marker"

    @property
    def shared_state_dir(self) -> Path:
        return self.home / ".local" / "state" / "pretender"

    @property
    def shared_lock_path(self) -> Path:
        return self.shared_state_dir / ".wizard.lock"


class RunnerProtocol(Protocol):
    def run(
        self,
        argv: Sequence[str],
        *,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        check: bool = True,
        capture_output: bool = False,
    ) -> Any:
        ...


def _text(value: str, label: str) -> str:
    if not isinstance(value, str) or any(
        ord(char) < 32 or ord(char) == 127 for char in value
    ):
        raise DeployError(f"{label} contains control characters")
    return value


def trusted_project_root() -> Path:
    """Return this checkout's root, never the caller's current directory."""

    root = Path(__file__).resolve().parents[1]
    manifest = root / "pyproject.toml"
    if _manifest_project_name(manifest) != "pretender":
        raise DeployError(f"trusted project root is not Pretender: {root}")
    return root


def _manifest_project_name(manifest: Path) -> str | None:
    """Read ``[project] name`` from pyproject.toml, with a 3.10 fallback."""

    try:
        raw = manifest.read_bytes()
    except OSError as exc:
        raise DeployError(f"trusted project root is invalid: {manifest}") from exc
    if tomllib is not None:
        try:
            project = tomllib.loads(raw.decode("utf-8")).get("project", {})
        except (UnicodeDecodeError, tomllib.TOMLDecodeError) as exc:
            raise DeployError(f"trusted project root is invalid: {manifest}") from exc
        return project.get("name") if isinstance(project, dict) else None
    section = ""
    for line in raw.decode("utf-8", "replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1].strip()
            continue
        if section != "project":
            continue
        match = re.fullmatch(r'name\s*=\s*"([^"]*)"', stripped)
        if match:
            return match.group(1)
    return None


def validate_model_id(value: str) -> str:
    raw = _text(value, "model ID")
    value = raw.strip()
    if not value:
        raise DeployError("model ID must not be empty")
    if raw != value or not value.isprintable():
        raise DeployError("model ID must be nonempty and printable")
    if len(value) > _MODEL_MAX:
        raise DeployError(f"model ID is too long (maximum {_MODEL_MAX} characters)")
    return value


def _is_loopback(host: str | None) -> bool:
    if not host:
        return False
    if host.lower().rstrip(".") == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def validate_base_url(value: str, *, allow_http_loopback: bool = False) -> str:
    value = _text(value, "base URL").strip()
    if any(char.isspace() for char in value):
        raise DeployError("base URL must not contain whitespace")
    try:
        parsed = urlsplit(value)
        host = parsed.hostname
    except ValueError as exc:
        raise DeployError("base URL is malformed") from exc
    if parsed.scheme not in ("http", "https") or not parsed.netloc or not host:
        raise DeployError("base URL must be an absolute http or https URL")
    if parsed.username is not None or parsed.password is not None:
        raise DeployError("base URL must not contain credentials")
    try:
        parsed.port
    except ValueError as exc:
        raise DeployError("base URL has an invalid port") from exc
    if parsed.query or parsed.fragment:
        raise DeployError("base URL must not contain a query or fragment")
    if parsed.scheme == "http" and not (
        allow_http_loopback and _is_loopback(host)
    ):
        raise DeployError("plain http is permitted only for an explicitly confirmed loopback endpoint")
    return value


def validate_secret(value: str, label: str) -> str:
    """Validate the deliberately small raw ``KEY=value`` secret alphabet."""

    value = _text(value, label)
    if not value or not _SECRET_CHARS.fullmatch(value):
        raise DeployError(
            f"{label} must be nonempty and contain only Docker/systemd-safe "
            "characters (letters, numbers, . _ - / + = : @ %)"
        )
    return value


def validate_image_reference(value: str) -> str:
    """Require a tagged or digest-pinned Docker image reference.

    A deployment must not silently float to ``latest`` (or to a registry's
    implicit tag).  Digest references may include a tag as well, but the
    digest is what makes the selected image immutable.
    """

    value = _text(value, "image")
    if value != value.strip():
        raise DeployError("image reference must not contain surrounding whitespace")
    if not value:
        raise DeployError("image reference must not be empty")
    if not _IMAGE_REFERENCE.fullmatch(value):
        raise DeployError("image reference contains unsupported characters")

    if value.count("@"):
        if value.count("@") != 1:
            raise DeployError("image reference has more than one digest")
        name, digest = value.split("@", 1)
        if not name or not _IMAGE_DIGEST.fullmatch(digest):
            raise DeployError("image digest must be an explicit hexadecimal digest")
        if re.search(r"(?:^|:)latest(?:@|$)", name, re.IGNORECASE):
            raise DeployError("image tag 'latest' is not allowed; use a pinned tag or digest")
    else:
        final_component = value.rsplit("/", 1)[-1]
        if ":" not in final_component:
            raise DeployError("image reference must include an explicit tag or digest")
        tag = final_component.rsplit(":", 1)[1]
        if not _IMAGE_TAG.fullmatch(tag):
            raise DeployError("image tag is malformed")
        if tag.lower() == "latest":
            raise DeployError("image tag 'latest' is not allowed; use a pinned tag or digest")

    return value


def toml_string(value: str, label: str = "value") -> str:
    """Return a safe TOML basic string, rejecting rather than hiding controls."""

    _text(value, label)
    return json.dumps(value, ensure_ascii=False)


def render_config(
    provider: Provider,
    features: Features,
    storage_path: str,
    port: int = DEFAULT_PORT,
) -> str:
    """Render the minimal config; secrets are represented by one fixed ref."""

    port = validate_port(port)
    base_url = validate_base_url(
        provider.base_url, allow_http_loopback=provider.http_loopback_confirmed
    )
    planner = validate_model_id(provider.planner_model)
    reply = validate_model_id(provider.reply_model)
    validate_secret(provider.api_key, "API key")
    _text(storage_path, "storage path")
    pipeline = ["sanitize"]
    if features.splitting:
        pipeline.append("split")
    if features.typo:
        pipeline.append("typo")
    pipeline_toml = "[" + ", ".join(toml_string(item) for item in pipeline) + "]"
    max_split = 3 if features.splitting else 1
    # MaiBot's chinese_typo.error_rate. 0.03 was three times too high and
    # produced a visibly misspelling bot.
    typo_rate = 0.01 if features.typo else 0.0
    caps = provider_capabilities(base_url)
    vision = provider.vision_model or caps.get("vision", "")
    embed = provider.embed_model or caps.get("embed", "")
    return "\n".join(
        [
            f"# {WIZARD_MARKER}",
            "",
            "# The bot's own name. It is what the gate matches on for a name",
            "# mention, and what the prompts call it.",
            "[bot]",
            f"name = {toml_string(DEFAULT_BOT_NAME, 'bot name')}",
            "",
            "# When the bot speaks. A direct @ or a quote of its own message",
            "# ALWAYS replies and ignores everything below.",
            "#   trigger_score - the score needed to speak unprompted (0-100).",
            "#                   Lower = chattier. A name mention scores 80, a",
            "#                   private chat 40, an unaddressed group message",
            "#                   0 plus content and pressure bonuses.",
            "#   threshold     - how many unanswered messages count as 'a lot'.",
            "#                   Pressure reaches 50 at this count, so a smaller",
            "#                   threshold makes the bot join in sooner.",
            "#   frequency     - a global damper: scales every score by",
            "#                   0.5 + 0.5*frequency. 1.0 = no damping.",
            "# Defaults below answer when addressed and otherwise chime in on a",
            "# busy conversation. For a chattier bot try threshold = 4 with",
            "# trigger_score = 55; for @-only set trigger_score = 100.",
            "[gate]",
            f"threshold = {DEFAULT_GATE_THRESHOLD}",
            f"trigger_score = {DEFAULT_GATE_TRIGGER_SCORE}",
            "frequency = 1.0",
            "",
            "# JSONL logs, also echoed to stdout (docker logs / ./deploy.sh logs).",
            "# Raise to \"DEBUG\" when diagnosing why the bot did or did not speak.",
            "[log]",
            'dir = "logs"',
            'level = "INFO"',
            "",
            "[llm.profiles.planner]",
            f"base_url = {toml_string(base_url, 'base URL')}",
            f"api_key = \"${{{LLM_ENV}}}\"",
            f"model = {toml_string(planner, 'planner model')}",
            "",
            "[llm.profiles.reply]",
            f"base_url = {toml_string(base_url, 'base URL')}",
            f"api_key = \"${{{LLM_ENV}}}\"",
            f"model = {toml_string(reply, 'reply model')}",
            "",
            "[output]",
            f"pipeline = {pipeline_toml}",
            f"max_split = {max_split}",
            f"typo_rate = {typo_rate}",
            "",
            *_vision_section(base_url, vision),
            *_embed_section(base_url, embed),
            "# Learn how this group actually talks: expression style, slang,",
            "# behaviour patterns, conversation summaries, and whether the",
            "# references shown to the planner were actually used.",
            "# Without this the reply style is frozen at \"自然\" forever.",
            "# 学习这个群的说话方式；关掉的话回复风格永远是\"自然\"。",
            "[learn]",
            f"enabled = {str(features.learning).lower()}",
            "cadence_s = 3600",
            "",
            *_learn_profiles(features.learning),
            "# Attention drift: how far the bot's attention wanders from the",
            "# current topic before coming back. Injected into both prompts.",
            "#   level    - subtle | active | scattered | wild",
            "#   anchor   - strict | balanced | loose   (how firmly it returns)",
            "#   reaction - reserved | natural | lively (short interjections)",
            "# 注意力漂移：话题跳跃的程度。",
            "[drift]",
            'level = "active"',
            'anchor = "balanced"',
            'reaction = "natural"',
            "",
            "# Emoji, stickers and image replies. Needs a vision profile to",
            "# describe what an incoming image actually contains.",
            "# 表情包与图片回复，需要 vision 配置。",
            "[media]",
            f"enabled = {str(features.media_enabled and bool(vision)).lower()}",
            "",
            "[adapter]",
            'name = "onebot"',
            "",
            "[adapter.onebot]",
            'mode = "reverse_ws"',
            'host = "127.0.0.1"',
            f"port = {port}",
            f"path = {toml_string(DEFAULT_ONEBOT_PATH, 'onebot path')}",
            f'access_token = "${{{ONEBOT_ENV}}}"',
            "",
            "[storage]",
            f"db_path = {toml_string(storage_path, 'storage path')}",
            "",
        ]
    )


def _vision_section(base_url: str, model: str) -> list[str]:
    """The vision profile, or a comment saying why there is none.

    A commented-out section beats a silently absent one: the next operator
    can see the capability was considered and why it is off.
    """
    if not model:
        return [
            "# No vision profile: this provider serves no model that accepts",
            "# image input, so incoming images cannot be described and",
            "# [media] stays off. 该提供商没有支持图片输入的模型。",
            "# [llm.profiles.vision]",
            "# base_url = ...",
            "# model = ...",
            "",
        ]
    return [
        "# Describes incoming images. Vision is a SEPARATE capability from",
        "# chat — the reply model above may reject image input entirely.",
        "# 识别图片内容；与聊天模型是两种能力。",
        "[llm.profiles.vision]",
        f"base_url = {toml_string(base_url, 'base URL')}",
        f"api_key = \"${{{LLM_ENV}}}\"",
        f"model = {toml_string(model, 'vision model')}",
        "",
    ]


def _embed_section(base_url: str, model: str) -> list[str]:
    """The embedding profile, or a comment saying why there is none."""
    if not model:
        return [
            "# No embed profile: this provider has no /embeddings endpoint,",
            "# so semantic memory recall and expression selection fall back",
            "# to full-text search and record weight. Everything still works,",
            "# it just matches on words rather than meaning.",
            "# 该提供商没有 /embeddings 接口，记忆检索退化为全文搜索。",
            "# [llm.profiles.embed]",
            "# base_url = ...",
            "# model = ...",
            "",
        ]
    return [
        "# Embeddings for semantic memory recall and expression selection.",
        "[llm.profiles.embed]",
        f"base_url = {toml_string(base_url, 'base URL')}",
        f"api_key = \"${{{LLM_ENV}}}\"",
        f"model = {toml_string(model, 'embed model')}",
        "",
    ]


#: The five learners, with MaiBot's cadences. Expression and jargon run
#: often (a group's slang moves fast); summary and effect are cheaper to
#: run rarely.
_LEARN_PROFILES = (
    ("expression", 1800),
    ("behavior", 3600),
    ("jargon", 3600),
    ("summary", 7200),
    ("effect", 7200),
)


def _learn_profiles(enabled: bool) -> list[str]:
    if not enabled:
        return []
    lines: list[str] = []
    for name, cadence in _LEARN_PROFILES:
        lines.append(f"[learn.profiles.{name}]")
        lines.append(f"cadence_s = {cadence}")
        lines.append("")
    return lines


def _dotenv_value(value: str, label: str) -> str:
    value = validate_secret(value, label)
    if "\n" in value or "\r" in value or "\x00" in value:
        raise DeployError(f"{label} contains a newline or NUL")
    return value


def render_docker_environment(plan: DeploymentPlan) -> str:
    """Render the project .env without exposing it in wizard output.

    The generated config and environment use one generic LLM key name for all
    provider presets.
    """

    image = _dotenv_value(plan.image, "image")
    key = _dotenv_value(plan.provider.api_key, "LLM secret")
    token = _dotenv_value(plan.onebot_token, "OneBot secret")
    lines = [
        f"# {WIZARD_MARKER}",
        f"PRETENDER_IMAGE={image}",
        f"{LLM_ENV}={key}",
        f"{ONEBOT_ENV}={token}",
        "",
    ]
    return "\n".join(lines)


def render_systemd_environment(plan: DeploymentPlan) -> str:
    """Serialize environment values using systemd EnvironmentFile quoting."""

    values = {LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token}
    lines = [f"# {WIZARD_MARKER}"]
    for key, value in values.items():
        if not _ENV_KEY.fullmatch(key):
            raise DeployError(f"invalid environment variable name {key!r}")
        value = validate_secret(value, f"{key} secret")
        if "\n" in value or "\r" in value or "\x00" in value:
            raise DeployError(f"{key} contains a newline or NUL")
        lines.append(f"{key}={escape_systemd_value(value)}")
    lines.append("")
    return "\n".join(lines)


def escape_systemd_value(value: str) -> str:
    """Escape a systemd EnvironmentFile value; newline and NUL are forbidden."""

    if not isinstance(value, str):
        raise DeployError("systemd environment value must be a string")
    if "\n" in value or "\r" in value or "\x00" in value:
        raise DeployError("systemd environment values must not contain newline or NUL")
    _text(value, "systemd environment value")
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
    )


def render_systemd_unit(plan: DeploymentPlan) -> str:
    if plan.native_service != "systemd":
        raise DeployError("systemd unit requested for a foreground plan")
    executable = _safe_systemd_path(plan.venv_path / "bin" / "pretender")
    config = _safe_systemd_path(plan.config_path)
    environment = _safe_systemd_path(plan.environment_path)
    return "\n".join(
        [
            f"# {WIZARD_MARKER}",
            "[Unit]",
            "Description=Pretender live bot",
            "After=network-online.target",
            "StartLimitIntervalSec=60",
            "StartLimitBurst=3",
            "",
            "[Service]",
            "Type=simple",
            f"ExecStart={executable} run --live --config {config}",
            f"EnvironmentFile={environment}",
            "Restart=on-failure",
            "RestartSec=10",
            "TimeoutStopSec=30",
            "UMask=0077",
            "NoNewPrivileges=true",
            "PrivateTmp=true",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )


def build_plan(
    target: str,
    provider: Provider,
    features: Features,
    onebot_token: str,
    *,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    image: str = DEFAULT_IMAGE,
    native_service: str = "foreground",
    port: int = DEFAULT_PORT,
) -> DeploymentPlan:
    if target not in {"compose", "docker", "native"}:
        raise DeployError("target must be compose, docker, or native")
    if native_service not in {"foreground", "systemd"}:
        raise DeployError("native service must be foreground or systemd")
    if target != "native":
        native_service = "foreground"
    provider = Provider(
        validate_base_url(
            provider.base_url, allow_http_loopback=provider.http_loopback_confirmed
        ),
        validate_model_id(provider.planner_model),
        validate_model_id(provider.reply_model),
        validate_secret(provider.api_key, "API key"),
        provider.http_loopback_confirmed,
    )
    token = validate_secret(onebot_token, "OneBot token")
    root = trusted_project_root() if project_root is None else Path(project_root)
    root = root.resolve()
    home_path = Path.home() if home is None else Path(home).resolve()
    if target == "native":
        config = home_path / ".config" / "pretender" / "config.toml"
        env = home_path / ".config" / "pretender" / "environment"
        storage = str(home_path / ".local" / "state" / "pretender" / "pretender.db")
    else:
        config = root / "config" / "config.toml"
        env = root / ".env"
        storage = "data/pretender.db"
    image = validate_image_reference(image)
    return DeploymentPlan(
        target=target,
        provider=provider,
        features=features,
        onebot_token=token,
        project_root=root,
        config_path=config,
        environment_path=env,
        storage_path=storage,
        image=image,
        native_service=native_service,
        home=home_path,
        port=validate_port(port),
    )


def docker_compose_commands(plan: DeploymentPlan) -> list[list[str]]:
    if plan.target != "compose":
        raise DeployError("Compose commands requested for another target")
    compose = [
        "docker", "compose", "-f", str(plan.project_root / "docker-compose.yml"),
        "--project-directory", str(plan.project_root),
    ]
    return [
        ["docker", "info"],
        ["docker", "volume", "create", "pretender-data"],
        compose + ["config", "--quiet"],
        compose + ["pull"],
        compose + ["run", "--rm", "--no-deps", "pretender", "init", "--config", "/config/config.toml"],
        compose + ["up", "-d"],
    ]


def docker_run_commands(plan: DeploymentPlan) -> list[list[str]]:
    if plan.target != "docker":
        raise DeployError("docker run commands requested for another target")
    config_mount = f"type=bind,src={plan.config_path.resolve()},dst=/config/config.toml,readonly"
    data_mount = "type=volume,src=pretender-data,dst=/config/data"
    init = [
        "docker", "run", "--rm", "--network", "host", "--env-file",
        str(plan.environment_path.resolve()), "--mount", config_mount,
        "--mount", data_mount, plan.image,
        "init", "--config", "/config/config.toml",
    ]
    return [
        ["docker", "info"],
        ["docker", "volume", "create", "pretender-data"],
        ["docker", "pull", plan.image],
        ["docker", "container", "inspect", "pretender"],
        init,
        [
            "docker",
            "run",
            "--name",
            "pretender",
            "--detach",
            "--network",
            "host",
            "--restart",
            "unless-stopped",
            "--label",
            "io.pretender.wizard-managed=true",
            "--env-file",
            str(plan.environment_path.resolve()),
            "--mount",
            config_mount,
            "--mount",
            data_mount,
            plan.image,
            "run",
            "--live",
            "--config",
            "/config/config.toml",
        ],
    ]


def docker_run_init_command(plan: DeploymentPlan) -> list[str]:
    if plan.target != "docker":
        raise DeployError("docker run init requested for another target")
    config_mount = f"type=bind,src={plan.config_path.resolve()},dst=/config/config.toml,readonly"
    data_mount = "type=volume,src=pretender-data,dst=/config/data"
    return [
        "docker", "run", "--rm", "--network", "host", "--env-file",
        str(plan.environment_path.resolve()), "--mount", config_mount,
        "--mount", data_mount, plan.image,
        "init", "--config", "/config/config.toml",
    ]


def native_init_command(plan: DeploymentPlan, venv_path: Path | None = None) -> list[str]:
    executable_root = venv_path or plan.venv_path
    return [
        str(executable_root / "bin" / "pretender"),
        "init",
        "--config",
        str(plan.config_path.resolve()),
    ]


class CommandRunner:
    def run(
        self,
        argv: Sequence[str],
        *,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        check: bool = True,
        capture_output: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            list(argv),
            cwd=str(cwd) if cwd is not None else None,
            env=dict(env) if env is not None else None,
            check=check,
            capture_output=capture_output,
            text=True,
        )


def _run(
    runner: RunnerProtocol,
    argv: Sequence[str],
    *,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
    check: bool = True,
    capture_output: bool = False,
) -> subprocess.CompletedProcess[str]:
    return runner.run(argv, cwd=cwd, env=env, check=check, capture_output=capture_output)


def _wizard_owned(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8") as stream:
            return WIZARD_MARKER in stream.read(4096)
    except (OSError, UnicodeError):
        return False


def _backup_path(path: Path) -> Path:
    candidate = path.with_name(path.name + ".bak")
    index = 1
    while candidate.exists() or candidate.is_symlink():
        candidate = path.with_name(path.name + f".bak.{index}")
        index += 1
    return candidate


def atomic_write(path: str | Path, content: str, *, mode: int = 0o644, force: bool = False) -> None:
    """Atomically write one regular target, backing up only wizard files."""

    _commit_artifacts([(Path(path), content, mode)], force=force)


def _check_parent_components(path: Path, root: Path) -> None:
    """Reject symlinked components between a deployment root and a target."""

    root = root.absolute()
    parent = path.absolute().parent
    try:
        relative = parent.relative_to(root)
    except ValueError as exc:
        raise DeployError(f"deployment target escapes its root: {path}") from exc
    current = root
    for component in relative.parts:
        current /= component
        if current.is_symlink():
            raise DeployError(f"refusing symlinked parent component {current}")
        if current.exists() and not current.is_dir():
            raise DeployError(f"deployment parent is not a directory: {current}")


def _preflight_destination(path: Path, *, force: bool) -> None:
    for parent in path.parents:
        if parent.is_symlink():
            raise DeployError(f"refusing symlinked parent component {parent}")
    if path.is_symlink():
        raise DeployError(f"refusing symlink target {path}")
    if path.exists() and not path.is_file():
        raise DeployError(f"refusing non-regular target {path}")
    if path.exists():
        if not force:
            raise DeployError(f"refusing to overwrite {path}; use --force")
        if not _wizard_owned(path):
            raise DeployError(f"refusing to replace non-wizard file {path}")
        _backup_path(path)  # reserve/check the backup naming policy before writes


def _stage_artifacts(
    artifacts: Sequence[tuple[Path, str, int]], *, force: bool, root: Path | None = None
) -> list[tuple[Path, Path, bool, Path | None]]:
    paths = [path for path, _, _ in artifacts]
    if len(set(paths)) != len(paths):
        raise DeployError("duplicate deployment artifact destination")
    for path in paths:
        if root is not None:
            _check_parent_components(path, root)
        _preflight_destination(path, force=force)
    staged: list[tuple[Path, Path, bool, Path | None]] = []
    temporary_paths: list[Path] = []
    try:
        for destination, content, mode in artifacts:
            destination.parent.mkdir(parents=True, exist_ok=True)
            fd, temporary = tempfile.mkstemp(
                prefix=f".{destination.name}.", dir=destination.parent
            )
            temporary_path = Path(temporary)
            temporary_paths.append(temporary_path)
            os.fchmod(fd, mode)
            with os.fdopen(fd, "wb") as stream:
                stream.write(content.encode("utf-8"))
                stream.flush()
                os.fsync(stream.fileno())
            staged.append((destination, temporary_path, destination.exists(), None))
    except BaseException:
        for temporary in temporary_paths:
            try:
                temporary.unlink()
            except OSError:
                pass
        raise
    return staged


@dataclass
class _ArtifactRecord:
    destination: Path
    existed: bool
    backup: Path | None
    secret: bool = False


@dataclass
class _ArtifactReceipt:
    records: list[_ArtifactRecord]

    def rollback(self) -> None:
        failures: list[str] = []
        for record in reversed(self.records):
            try:
                if record.existed and record.backup is not None:
                    os.replace(record.backup, record.destination)
                elif record.destination.is_file() and not record.destination.is_symlink():
                    record.destination.unlink()
            except OSError as exc:
                failures.append(str(exc))
        if failures:
            raise DeployError(
                "artifact rollback failed; private backups were preserved: "
                + "; ".join(failures)
            )
        for record in self.records:
            if record.backup is not None and record.backup.exists():
                try:
                    record.backup.unlink()
                except OSError:
                    pass


def _private_secret_backup(path: Path, content: bytes, root: Path) -> Path:
    backup_dir = root / ".local" / "state" / "pretender" / "deploy-backups"
    _check_parent_components(backup_dir / "env", root)
    if backup_dir.is_symlink() or (backup_dir.exists() and not backup_dir.is_dir()):
        raise DeployError(f"refusing unsafe private backup directory {backup_dir}")
    backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(backup_dir, 0o700)
    fd, temporary = tempfile.mkstemp(prefix=".environment.", suffix=".backup", dir=backup_dir)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        try:
            os.close(fd)
        except OSError:
            pass
        try:
            Path(temporary).unlink()
        except OSError:
            pass
        raise
    return Path(temporary)


def _commit_artifacts(
    artifacts: Sequence[tuple[Path, str, int]], *, force: bool,
    root: Path | None = None, secret_paths: set[Path] | None = None,
    secret_backup_root: Path | None = None,
) -> _ArtifactReceipt:
    staged = _stage_artifacts(artifacts, force=force, root=root)
    committed: list[_ArtifactRecord] = []
    backups: list[Path] = []
    secret_paths = secret_paths or set()
    try:
        for destination, temporary, existed, _ in staged:
            backup = None
            if existed:
                if destination in secret_paths:
                    if secret_backup_root is None:
                        raise DeployError("private secret backup root is required")
                    backup = _private_secret_backup(
                        destination, destination.read_bytes(), secret_backup_root
                    )
                else:
                    backup = _backup_path(destination)
                    shutil.copy2(destination, backup)
                backups.append(backup)
            os.replace(temporary, destination)
            committed.append(_ArtifactRecord(destination, existed, backup, destination in secret_paths))
            os.chmod(destination, next(mode for path, _, mode in artifacts if path == destination))
    except BaseException:
        try:
            _ArtifactReceipt(committed).rollback()
        except DeployError:
            raise
        for backup in backups:
            if backup.exists():
                try:
                    backup.unlink()
                except OSError:
                    pass
        for destination, temporary, _, _ in staged:
            if temporary.exists():
                try:
                    temporary.unlink()
                except OSError:
                    pass
        raise
    finally:
        for _, temporary, _, _ in staged:
            if temporary.exists():
                try:
                    temporary.unlink()
                except OSError:
                    pass
    return _ArtifactReceipt(committed)


def _write_artifacts(plan: DeploymentPlan, *, force: bool) -> _ArtifactReceipt:
    artifacts: list[tuple[Path, str, int]] = [
        (
            plan.config_path,
            render_config(plan.provider, plan.features, plan.storage_path, plan.port),
            0o644,
        ),
    ]
    if plan.target == "native":
        artifacts.append((plan.environment_path, render_systemd_environment(plan), 0o600))
    else:
        artifacts.append((plan.environment_path, render_docker_environment(plan), 0o600))
    if plan.target == "native" and not plan.venv_path.exists():
        artifacts.append((plan.venv_marker_path, f"# {WIZARD_MARKER}\n", 0o600))
    if plan.target == "native" and plan.native_service == "systemd":
        artifacts.append((plan.unit_path, render_systemd_unit(plan), 0o600))
    root = plan.project_root if plan.target in {"compose", "docker"} else plan.home
    secret_paths = {plan.environment_path}
    return _commit_artifacts(
        artifacts,
        force=force,
        root=root,
        secret_paths=secret_paths,
        secret_backup_root=plan.home,
    )


def _ensure_venv(path: Path) -> None:
    if path.is_symlink():
        raise DeployError(f"refusing symlink virtual environment {path}")
    if path.exists() and not path.is_dir():
        raise DeployError(f"virtual environment target is not a directory: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)


def _ensure_private_config_dir(plan: DeploymentPlan) -> None:
    if plan.target != "native":
        return
    directory = plan.environment_path.parent
    _check_parent_components(directory / "environment", plan.home)
    if directory.is_symlink() or (directory.exists() and not directory.is_dir()):
        raise DeployError(f"native config directory is not a private directory: {directory}")
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    if directory.is_symlink():
        raise DeployError(f"refusing symlinked native config directory {directory}")
    os.chmod(directory, 0o700)


def _ensure_private_state_dir(plan: DeploymentPlan) -> Path:
    if plan.target != "native":
        raise DeployError("native state directory requested for a Docker plan")
    state_dir = Path(plan.storage_path).parent
    shared_state_dir = _ensure_private_user_state_dir(plan.home)
    if state_dir != shared_state_dir:
        raise DeployError("native state directory is not the shared deployment state root")
    _check_parent_components(state_dir / "pretender.db", plan.home)
    return state_dir


def _ensure_private_user_state_dir(home: Path) -> Path:
    state_dir = home / ".local" / "state" / "pretender"
    _check_parent_components(state_dir / ".wizard.lock", home)
    if state_dir.is_symlink() or (state_dir.exists() and not state_dir.is_dir()):
        raise DeployError(f"private deployment state directory is unsafe: {state_dir}")
    state_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    if state_dir.is_symlink():
        raise DeployError(f"refusing symlinked deployment state directory {state_dir}")
    os.chmod(state_dir, 0o700)
    return state_dir


def _secure_native_database(plan: DeploymentPlan) -> None:
    database = Path(plan.storage_path)
    for path in (database, Path(f"{database}-wal"), Path(f"{database}-shm")):
        if path.is_symlink():
            raise DeployError(f"refusing symlinked native database file {path}")
        if path.exists():
            if not path.is_file():
                raise DeployError(f"native database sidecar is not a regular file: {path}")
            os.chmod(path, 0o600)


def _run_with_umask(
    runner: RunnerProtocol,
    argv: Sequence[str],
    *,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> Any:
    old_umask = os.umask(0o077)
    try:
        return _run(runner, argv, cwd=cwd, env=env)
    finally:
        os.umask(old_umask)


def _cleanup_new_venv(plan: DeploymentPlan, *, existed: bool, marker_existed: bool) -> None:
    if existed or plan.venv_path.is_symlink():
        return
    marker = plan.venv_marker_path
    owned_marker = marker.is_file() and _wizard_owned(marker)
    if not owned_marker:
        return
    if plan.venv_path.is_dir() and not plan.venv_path.is_symlink():
        shutil.rmtree(plan.venv_path)
    if not marker_existed and marker.is_file() and _wizard_owned(marker):
        marker.unlink()


def _preflight_venv(plan: DeploymentPlan, *, force: bool) -> None:
    marker = plan.venv_marker_path
    if plan.venv_path.is_symlink():
        raise DeployError(f"refusing symlink virtual environment {plan.venv_path}")
    if plan.venv_path.exists() and not plan.venv_path.is_dir():
        raise DeployError(f"virtual environment target is not a directory: {plan.venv_path}")
    if marker.is_symlink():
        raise DeployError(f"refusing symlink virtual environment marker {marker}")
    if plan.venv_path.exists() and (
        not marker.is_file() or not _wizard_owned(marker)
    ):
        raise DeployError("existing virtual environment is not wizard-owned")
    if not plan.venv_path.exists() and marker.exists():
        _preflight_destination(marker, force=force)


def _safe_systemd_path(path: Path) -> str:
    value = str(path.resolve())
    if not value.startswith("/"):
        raise DeployError("systemd paths must be absolute")
    if any(char.isspace() or char in "'\"\\$`" for char in value):
        raise DeployError(f"systemd path contains unsupported characters: {value}")
    return value


def controlled_compose_env(plan: DeploymentPlan) -> dict[str, str]:
    """Inherit ordinary process settings but control every deployment secret."""

    environment = dict(os.environ)
    environment.update(
        {
            "PRETENDER_IMAGE": plan.image,
            LLM_ENV: plan.provider.api_key,
            ONEBOT_ENV: plan.onebot_token,
        }
    )
    return environment


def _compose_command(plan: DeploymentPlan, *args: str) -> list[str]:
    return [
        "docker",
        "compose",
        "-f",
        str(plan.project_root / "docker-compose.yml"),
        "--project-directory",
        str(plan.project_root),
        *args,
    ]


def validate_port(value: Any) -> int:
    """Return an unprivileged TCP port, rejecting anything else."""

    if isinstance(value, bool):
        raise DeployError(t("error.port"))
    if isinstance(value, str):
        text = _text(value, "port").strip()
        if not text.isdigit():
            raise DeployError(t("error.port"))
        value = int(text)
    if not isinstance(value, int) or not 1024 <= value <= 65535:
        raise DeployError(t("error.port"))
    return value


def port_available(port: int, host: str = "127.0.0.1", *, timeout: float = 0.25) -> bool:
    """Return whether a listener could bind ``host:port`` right now."""

    port = validate_port(port)
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.settimeout(timeout)
        sock.bind((host, port))
    except OSError:
        return False
    finally:
        sock.close()
    return True


def describe_port_holder(port: int, *, timeout: float = 3.0) -> str:
    """Best-effort name of whatever is listening on a port; never raises.

    A busy 3002 is the most common first-run failure, so naming the holder
    turns a dead end into an obvious next step.  Missing tooling, permission
    limits and odd output all degrade to an empty string.
    """

    try:
        port = validate_port(port)
    except DeployError:
        return ""
    executable = shutil.which("ss")
    argv = [executable, "-ltnpH"] if executable else None
    if argv is None:
        executable = shutil.which("lsof")
        if executable is None:
            return ""
        argv = [executable, "-nP", f"-iTCP:{port}", "-sTCP:LISTEN"]
    try:
        completed = subprocess.run(
            argv, capture_output=True, text=True, timeout=timeout, check=False
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    for line in (completed.stdout or "").splitlines():
        if f":{port} " not in f"{line} ":
            continue
        match = re.search(r'"([^"]{1,64})",pid=(\d{1,10})', line)
        if match:
            return f"{match.group(1)} pid={match.group(2)}"
        fields = line.split()
        if executable.endswith("lsof") and len(fields) >= 2:
            return f"{fields[0]} pid={fields[1]}"
    return ""


def _holder_suffix(port: int) -> str:
    holder = describe_port_holder(port)
    return t("port.holder", holder=holder) if holder else ""


def find_free_port(
    preferred: int = DEFAULT_PORT,
    host: str = "127.0.0.1",
    *,
    span: int = PORT_SCAN_SPAN,
) -> int:
    """Return ``preferred`` when it is free, else the next free port above it."""

    preferred = validate_port(preferred)
    for candidate in range(preferred, min(preferred + max(span, 1), 65536)):
        if port_available(candidate, host):
            return candidate
    raise DeployError(
        t("error.no_free_port", host=host, port=preferred, span=span)
    )


def check_listener(
    host: str = "127.0.0.1", port: int = DEFAULT_PORT, *, timeout: float = 0.25
) -> None:
    """Fail clearly when the reverse-WebSocket listener port is occupied."""

    if not port_available(port, host, timeout=timeout):
        raise DeployError(
            t("error.listener", host=host, port=port, holder=_holder_suffix(port))
        )


def _preflight_destinations(plan: DeploymentPlan, *, force: bool) -> None:
    root = plan.project_root if plan.target in {"compose", "docker"} else plan.home
    paths = [plan.config_path, plan.environment_path]
    if plan.target == "native":
        if not plan.venv_path.exists():
            paths.append(plan.venv_marker_path)
        if plan.native_service == "systemd":
            paths.append(plan.unit_path)
    for path in paths:
        _check_parent_components(path, root)
        _preflight_destination(path, force=force)
    if plan.target == "native":
        _check_parent_components(Path(plan.storage_path), plan.home)
        _preflight_venv(plan, force=force)


def _preflight_systemd(runner: RunnerProtocol) -> None:
    active = _run(
        runner,
        ["systemctl", "--user", "is-active", "--quiet", "pretender.service"],
        check=False,
    )
    if active.returncode == 0:
        raise DeployError("pretender.service is already active; refusing to replace it")
    enabled = _run(
        runner,
        ["systemctl", "--user", "is-enabled", "--quiet", "pretender.service"],
        check=False,
    )
    if enabled.returncode == 0:
        raise DeployError("pretender.service is already enabled; refusing to replace it")


def _wait_systemd_active(
    runner: RunnerProtocol, *, attempts: int = 3, delay: float = 0.05
) -> None:
    for attempt in range(attempts):
        active = _run(
            runner,
            ["systemctl", "--user", "is-active", "--quiet", "pretender.service"],
            check=False,
        )
        if active.returncode == 0:
            return
        if attempt + 1 < attempts:
            time.sleep(delay)
    raise DeployError("pretender.service did not become active after start")


def _preflight_docker(
    plan: DeploymentPlan,
    runner: RunnerProtocol,
    *,
    listener_checker: Callable[[], None],
) -> None:
    _run(runner, ["docker", "info"])
    running = _run(
        runner,
        ["docker", "ps", "--filter", "volume=pretender-data", "--format", "{{.Names}}"],
        capture_output=True,
    )
    if running.stdout.strip():
        raise DeployError("a running container already uses pretender-data; refusing to start")
    existing = _run(
        runner,
        ["docker", "container", "inspect", "pretender"],
        check=False,
        capture_output=True,
    )
    if existing.returncode == 0:
        raise DeployError("container named 'pretender' already exists; refusing to replace it")
    listener_checker()


class DockerDaemonLock:
    """A stopped, daemon-owned lock container held for one wizard session."""

    def __init__(self, runner: RunnerProtocol, image: str):
        self.runner = runner
        self.image = image
        self.acquired = False

    def acquire(self) -> None:
        if self.acquired:
            return
        _run(
            self.runner,
            [
                "docker", "create", "--name", WIZARD_LOCK_CONTAINER,
                "--label", WIZARD_LOCK_LABEL, "--entrypoint", "/bin/true",
                self.image,
            ],
        )
        self.acquired = True

    def release(self) -> None:
        if not self.acquired:
            return
        try:
            _run(self.runner, ["docker", "rm", WIZARD_LOCK_CONTAINER])
        finally:
            self.acquired = False


class SessionLockProtocol(Protocol):
    def acquire(self) -> None:
        ...

    def release(self) -> None:
        ...


class UserWizardLock:
    """A shared non-blocking lock for every kind of wizard session."""

    def __init__(self, plan: DeploymentPlan):
        self.plan = plan
        self.handle: Any | None = None

    def acquire(self) -> None:
        if self.handle is not None:
            return
        if fcntl is None:
            raise DeployError("native wizard locking is unavailable on this platform")
        state_dir = _ensure_private_user_state_dir(self.plan.home)
        path = self.plan.shared_lock_path
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise DeployError(f"refusing unsafe native wizard lock {path}")
        flags = os.O_CREAT | os.O_RDWR
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd: int | None = None
        try:
            fd = os.open(path, flags, 0o600)
            os.chmod(path, 0o600)
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except (BlockingIOError, OSError) as exc:
            if fd is not None:
                os.close(fd)
            if isinstance(exc, BlockingIOError) or getattr(exc, "errno", None) in {11, 13}:
                raise DeployError("another native deployment wizard is already running") from exc
            raise DeployError(f"cannot acquire native wizard lock: {path}") from exc
        self.handle = fd

    def release(self) -> None:
        if self.handle is None:
            return
        fd = self.handle
        self.handle = None
        try:
            assert fcntl is not None
            fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)


# Kept as a source-compatible name for callers of the earlier native-only API.
NativeWizardLock = UserWizardLock


def _new_venv_staging_path(plan: DeploymentPlan) -> Path:
    parent = plan.venv_path.parent
    _check_parent_components(plan.venv_path, plan.home)
    if parent.is_symlink() or (parent.exists() and not parent.is_dir()):
        raise DeployError(f"unsafe native venv parent {parent}")
    parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(parent, 0o700)
    return Path(tempfile.mkdtemp(prefix=".venv-staging-", dir=parent))


def _remove_staging_venv(path: Path | None) -> None:
    if path is not None and path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)


def promote_venv(plan: DeploymentPlan, staging: Path) -> None:
    """Atomically promote a completed venv, preserving an old one on failure."""

    final = plan.venv_path
    if staging.is_symlink() or not staging.is_dir():
        raise DeployError("venv staging path is not a regular directory")
    previous: Path | None = None
    if final.exists() or final.is_symlink():
        if final.is_symlink() or not final.is_dir():
            raise DeployError(f"unsafe native venv target {final}")
        if not plan.venv_marker_path.is_file() or not _wizard_owned(plan.venv_marker_path):
            raise DeployError("existing virtual environment is not wizard-owned")
        previous = final.with_name(f".venv-previous-{os.getpid()}")
        suffix = 1
        while previous.exists() or previous.is_symlink():
            previous = final.with_name(f".venv-previous-{os.getpid()}-{suffix}")
            suffix += 1
        os.replace(final, previous)
    try:
        os.replace(staging, final)
    except BaseException as exc:
        if previous is not None:
            try:
                os.replace(previous, final)
            except OSError as restore_error:
                raise DeployError("venv swap failed and the old venv could not be restored") from restore_error
        raise exc


def setup_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    force: bool = False,
    listener_checker: Callable[[], None] | None = None,
    docker_lock: SessionLockProtocol | None = None,
) -> DeploymentPlan:
    """Preflight and install artifacts, but never start a live process."""

    runner = runner or CommandRunner()
    listener_checker = listener_checker or (lambda: check_listener(port=plan.port))
    _preflight_destinations(plan, force=force)
    if plan.target in {"compose", "docker"}:
        _preflight_docker(plan, runner, listener_checker=listener_checker)
    else:
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            raise DeployError("native deployment must not be run as root")
        if plan.native_service == "systemd":
            _preflight_systemd(runner)
        listener_checker()
    own_docker_lock = False
    staging_venv: Path | None = None
    receipt: _ArtifactReceipt | None = None
    try:
        if plan.target in {"compose", "docker"}:
            if plan.target == "compose":
                pre_env = controlled_compose_env(plan)
                _run(runner, _compose_command(plan, "pull"), cwd=plan.project_root, env=pre_env)
            else:
                _run(runner, ["docker", "pull", plan.image])
            if docker_lock is None:
                docker_lock = DockerDaemonLock(runner, plan.image)
                own_docker_lock = True
            docker_lock.acquire()
        if plan.target == "native":
            _ensure_private_state_dir(plan)
        _ensure_private_config_dir(plan)
        receipt = _write_artifacts(plan, force=force)
        if plan.target in {"compose", "docker"}:
            _run(runner, ["docker", "volume", "create", "pretender-data"])
            if plan.target == "compose":
                env = controlled_compose_env(plan)
                _run(
                    runner,
                    _compose_command(plan, "config", "--quiet"),
                    cwd=plan.project_root,
                    env=env,
                )
                _run(
                    runner,
                    _compose_command(
                        plan, "run", "--rm", "--no-deps", "pretender", "init",
                        "--config", "/config/config.toml",
                    ),
                    cwd=plan.project_root,
                    env=env,
                )
            else:
                _run(runner, docker_run_init_command(plan), cwd=plan.project_root)
        else:
            staging_venv = _new_venv_staging_path(plan)
            staging_python = staging_venv / "bin" / "python"
            _run(runner, [sys.executable, "-m", "venv", str(staging_venv)])
            _run(runner, [str(staging_python), "-m", "pip", "install", str(plan.project_root)])
            native_env = {**os.environ, LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token}
            _run_with_umask(
                runner, native_init_command(plan, staging_venv),
                cwd=plan.project_root, env=native_env,
            )
            _secure_native_database(plan)
            promote_venv(plan, staging_venv)
            staging_venv = None
    except BaseException:
        _remove_staging_venv(staging_venv)
        if receipt is not None:
            receipt.rollback()
        raise
    finally:
        if own_docker_lock and docker_lock is not None:
            docker_lock.release()
    return plan


def start_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    listener_checker: Callable[[], None] | None = None,
    output: Callable[[str], None] = print,
) -> None:
    """Run only after the caller has obtained the second confirmation."""

    runner = runner or CommandRunner()
    listener_checker = listener_checker or (lambda: check_listener(port=plan.port))
    if plan.target in {"compose", "docker"}:
        _preflight_docker(plan, runner, listener_checker=listener_checker)
        if plan.target == "compose":
            _run(
                runner,
                _compose_command(plan, "up", "-d"),
                cwd=plan.project_root,
                env=controlled_compose_env(plan),
            )
        else:
            _run(runner, docker_run_commands(plan)[-1], cwd=plan.project_root)
        return
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        raise DeployError("native deployment must not be run as root")
    listener_checker()
    if plan.native_service == "systemd":
        _preflight_systemd(runner)
        _run(runner, ["systemctl", "--user", "daemon-reload"])
        _run(runner, ["systemctl", "--user", "enable", "pretender.service"])
        try:
            _run(runner, ["systemctl", "--user", "start", "pretender.service"])
            _wait_systemd_active(runner)
        except BaseException as start_error:
            try:
                _run(runner, ["systemctl", "--user", "disable", "pretender.service"])
            except BaseException as cleanup_error:
                raise DeployError(
                    "systemd start failed and disabling the service also failed"
                ) from cleanup_error
            raise start_error
        output(t("msg.systemd_linger"))
        return
    environment = dict(os.environ)
    environment.update({LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token})
    _run_with_umask(
        runner,
        [
            str(plan.venv_path / "bin" / "pretender"),
            "run",
            "--live",
            "--config",
            str(plan.config_path.resolve()),
        ],
        cwd=plan.project_root,
        env=environment,
    )


def apply_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    force: bool = False,
    output: Callable[[str], None] = print,
) -> None:
    """Set up artifacts and dependencies without starting a live process."""

    runner = runner or CommandRunner()
    setup_plan(plan, runner=runner, force=force)


def plan_summary(plan: DeploymentPlan) -> str:
    redacted = t("summary.redacted")
    lines = [
        t("summary.title"),
        f"  {t('summary.target')}: {plan.target}",
        f"  {t('summary.provider')}: {plan.provider.base_url}",
        f"  {t('summary.planner')}: {plan.provider.planner_model}",
        f"  {t('summary.reply')}: {plan.provider.reply_model}",
        f"  {t('summary.api_key')}: {redacted}",
        f"  {t('summary.token')}: {redacted}",
        f"  {t('summary.features')}: splitting={plan.features.splitting}, "
        f"typo={plan.features.typo}, media={plan.features.media_enabled}",
        f"  {t('summary.port')}: {plan.port}",
        f"  {t('summary.config')}: {plan.config_path.resolve()}",
        f"  {t('summary.storage')}: {plan.storage_path}",
    ]
    if plan.target in {"compose", "docker"}:
        lines.append(f"  {t('summary.image')}: {plan.image}")
    else:
        lines.append(f"  {t('summary.service')}: {plan.native_service}")
    return "\n".join(lines)


def token_reveal_command(plan: DeploymentPlan) -> str:
    """The one command that prints the stored OneBot token, and nothing else."""

    if plan.target == "compose":
        return "./deploy.sh token"
    path = plan.environment_path.resolve()
    return f"grep '^{ONEBOT_ENV}=' {path} | cut -d= -f2-"


def start_command(plan: DeploymentPlan) -> str:
    """The command that starts the deployment the wizard just installed."""

    if plan.target == "compose":
        return "./deploy.sh start"
    if plan.target == "docker":
        return f"docker start pretender  # {t('summary.image')}: {plan.image}"
    if plan.native_service == "systemd":
        return "systemctl --user start pretender.service"
    executable = plan.venv_path / "bin" / "pretender"
    return f"{executable} run --live --config {plan.config_path.resolve()}"


def napcat_instructions(plan: DeploymentPlan) -> str:
    """Print the exact NapCat wiring; the token itself is never printed."""

    return "\n".join(
        [
            t("msg.napcat_title"),
            t("msg.napcat_url", url=plan.onebot_url),
            t(
                "msg.napcat_token",
                env=ONEBOT_ENV,
                path=plan.environment_path.resolve(),
            ),
            t("msg.napcat_token_cmd", command=token_reveal_command(plan)),
            t("msg.napcat_docker"),
            t("msg.napcat_login"),
            t("msg.napcat_wait"),
        ]
    )


def manage_commands(plan: DeploymentPlan) -> str:
    """Post-install cheat sheet, matched to the target that was installed."""

    if plan.target == "compose":
        commands = [
            "./deploy.sh logs",
            "./deploy.sh status",
            "./deploy.sh stop",
            "./deploy.sh update",
        ]
    elif plan.target == "docker":
        commands = [
            "docker logs -f pretender",
            "docker ps --filter name=pretender",
            "docker stop -t 30 pretender",
        ]
    elif plan.native_service == "systemd":
        commands = [
            "journalctl --user -u pretender.service -f",
            "systemctl --user status pretender.service",
            "systemctl --user stop pretender.service",
        ]
    else:
        commands = [start_command(plan)]
    return "\n".join([t("msg.manage"), *(f"  {command}" for command in commands)])


Input = Callable[[str], str]


def _ask(input_fn: Input, prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    answer = input_fn(f"{prompt}{suffix}: ").strip()
    return default if answer == "" and default is not None else answer


def _yes_no(input_fn: Input, prompt: str, default: bool) -> bool:
    default_text = "Y/n" if default else "y/N"
    while True:
        answer = input_fn(f"{prompt} [{default_text}]: ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False


def _choice(
    input_fn: Input,
    prompt: str,
    choices: Mapping[str, str],
    default: str | None = None,
) -> str:
    while True:
        suffix = f"; {t('prompt.default')} {default}" if default is not None else ""
        answer = input_fn(f"{prompt} ({'/'.join(choices)}{suffix}): ").strip().lower()
        if not answer and default is not None:
            answer = default
        if answer in choices:
            return choices[answer]


def _prompt_port(
    input_fn: Input,
    output: Callable[[str], None],
    preferred: int = DEFAULT_PORT,
) -> int:
    """Offer a free port, and never accept one that is already taken.

    Port 3002 collides constantly (another OneBot bridge, a dev server), so
    the wizard probes upward for a free port and offers that as the default
    instead of failing later during startup.
    """

    suggested = find_free_port(preferred)
    if suggested != preferred:
        output(
            t(
                "port.busy",
                port=preferred,
                holder=_holder_suffix(preferred),
                chosen=suggested,
            )
        )
    while True:
        answer = _ask(input_fn, t("prompt.port"), str(suggested))
        try:
            candidate = validate_port(answer)
        except DeployError as exc:
            output(str(exc))
            continue
        if port_available(candidate):
            return candidate
        output(
            t(
                "error.listener",
                host="127.0.0.1",
                port=candidate,
                holder=_holder_suffix(candidate),
            )
        )
        suggested = find_free_port(candidate)


def _provider_defaults(kind: str, input_fn: Input) -> tuple[str, str | None]:
    if kind == "deepseek":
        return "https://api.deepseek.com/v1", "deepseek-chat"
    if kind == "openai":
        return "https://api.openai.com/v1", "gpt-4o-mini"
    return _ask(input_fn, t("prompt.base_url")), None


#: Known vision/embedding models per base URL. A provider absent here simply
#: gets no vision/embed profile — the wizard never guesses a model id that may
#: not exist.
#:
#: "Supports vision" means the model actually READS the image, not that the
#: endpoint accepts the request shape. On opencode.ai/zen, ``hy3-free``
#: returns HTTP 200 for an image part, reports ``prompt_tokens: 18`` for a
#: 256x256 PNG, and answers "您似乎没有上传图片" — it discards the image
#: silently. Probing for a 200 would have wrongly listed it here.
PROVIDER_CAPABILITIES: dict[str, dict[str, str]] = {
    # No /embeddings endpoint; deepseek-chat takes no image input.
    "https://api.deepseek.com/v1": {},
    "https://api.openai.com/v1": {
        "vision": "gpt-4o-mini",
        "embed": "text-embedding-3-small",
    },
    # No /embeddings endpoint at all (HTML 404), and no model that reads
    # images: every free model either 404s on image input or drops it.
    "https://opencode.ai/zen/v1": {},
}


def provider_capabilities(base_url: str) -> dict[str, str]:
    """The verified vision/embed models for ``base_url``, or an empty dict."""
    return PROVIDER_CAPABILITIES.get(base_url.rstrip("/"), {})


def _confirm_base_url(base_url: str, input_fn: Input) -> tuple[str, bool]:
    """Validate a base URL, allowing loopback HTTP only when confirmed."""

    try:
        validate_base_url(base_url)
    except DeployError:
        parts = urlsplit(base_url)
        if parts.scheme == "http" and _is_loopback(parts.hostname):
            if not _yes_no(input_fn, t("prompt.http_loopback"), False):
                raise DeployError(
                    "plain HTTP loopback endpoint was not confirmed"
                )
            validate_base_url(base_url, allow_http_loopback=True)
            return base_url, True
        raise
    return base_url, False


def gather_plan(
    *,
    input_fn: Input = input,
    secret_fn: Input = getpass.getpass,
    output: Callable[[str], None] = print,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    advanced: bool = False,
    port: int | None = None,
) -> DeploymentPlan:
    """Collect a plan.  The express path defaults everything that has a sane
    default; ``advanced`` asks the full set of questions instead."""

    target = _choice(
        input_fn,
        t("prompt.target"),
        {"1": "compose", "2": "docker", "3": "native"},
        default="1",
    )
    native_service = "foreground"
    if target == "native":
        native_service = _choice(
            input_fn,
            t("prompt.native_mode"),
            {"f": "foreground", "foreground": "foreground", "s": "systemd", "systemd": "systemd"},
            default="f",
        )
    provider_kind = _choice(
        input_fn,
        t("prompt.provider"),
        {"1": "deepseek", "2": "openai", "3": "custom"},
        default="1",
    )
    base_url, model_default = _provider_defaults(provider_kind, input_fn)
    base_url, http_loopback_confirmed = _confirm_base_url(base_url, input_fn)
    planner_model = _ask(input_fn, t("prompt.planner_model"), model_default)
    validate_model_id(planner_model)
    reply_model = planner_model
    if advanced:
        reply_model = _ask(input_fn, t("prompt.reply_model"), planner_model)
        if reply_model == "":
            reply_model = planner_model
    validate_model_id(reply_model)
    api_key = validate_secret(secret_fn(t("prompt.api_key")), "API key")
    token = secrets.token_hex(32)
    if advanced:
        supplied_token = secret_fn(t("prompt.onebot_token"))
        if supplied_token.strip():
            token = validate_secret(supplied_token, "OneBot token")
    chosen_port = (
        validate_port(port)
        if port is not None
        else _prompt_port(input_fn, output)
    )
    features = Features()
    image = DEFAULT_IMAGE
    if advanced:
        features = Features(
            _yes_no(input_fn, t("prompt.splitting"), True),
            _yes_no(input_fn, t("prompt.typo"), True),
            _yes_no(input_fn, t("prompt.media"), False),
        )
        if target in {"compose", "docker"}:
            image = _ask(input_fn, t("prompt.image"), DEFAULT_IMAGE)
    return build_plan(
        target,
        Provider(base_url, planner_model, reply_model, api_key, http_loopback_confirmed),
        features,
        token,
        project_root=project_root,
        home=home,
        image=image,
        native_service=native_service,
        port=chosen_port,
    )


def plan_from_options(
    *,
    target: str = "compose",
    provider_kind: str = "deepseek",
    base_url: str | None = None,
    planner_model: str | None = None,
    reply_model: str | None = None,
    port: int | None = None,
    image: str = DEFAULT_IMAGE,
    native_service: str = "foreground",
    features: Features | None = None,
    environ: Mapping[str, str] | None = None,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    api_key_env: str = LLM_ENV,
    token_env: str = ONEBOT_ENV,
) -> DeploymentPlan:
    """Build a plan without prompting, for scripted/unattended deployment.

    Secrets come from the environment, never from argv: a command line is
    visible in ``ps`` output and lands in shell history.
    """

    environ = os.environ if environ is None else environ
    if not _ENV_KEY.fullmatch(api_key_env) or not _ENV_KEY.fullmatch(token_env):
        raise DeployError("environment variable names must be identifier-shaped")
    api_key = (environ.get(api_key_env) or "").strip()
    if not api_key:
        raise DeployError(t("error.api_key_env", env=api_key_env))
    supplied_token = (environ.get(token_env) or "").strip()
    token = validate_secret(supplied_token, "OneBot token") if supplied_token else secrets.token_hex(32)
    if provider_kind == "deepseek":
        resolved_url, model_default = "https://api.deepseek.com/v1", "deepseek-chat"
    elif provider_kind == "openai":
        resolved_url, model_default = "https://api.openai.com/v1", "gpt-4o-mini"
    elif provider_kind == "custom":
        if not base_url:
            raise DeployError("a custom provider requires --base-url")
        resolved_url, model_default = base_url, None
    else:
        raise DeployError("provider must be deepseek, openai, or custom")
    resolved_url = base_url or resolved_url
    planner = planner_model or model_default
    if not planner:
        raise DeployError("a model ID is required (--model)")
    chosen_port = validate_port(port) if port is not None else find_free_port()
    return build_plan(
        target,
        Provider(resolved_url, planner, reply_model or planner, validate_secret(api_key, "API key")),
        features or Features(),
        token,
        project_root=project_root,
        home=home,
        image=image,
        native_service=native_service,
        port=chosen_port,
    )


def run_wizard(
    *,
    dry_run: bool = False,
    force: bool = False,
    input_fn: Input = input,
    secret_fn: Input = getpass.getpass,
    output: Callable[[str], None] = print,
    runner: RunnerProtocol | None = None,
    listener_checker: Callable[[], None] | None = None,
    session_lock: SessionLockProtocol | None = None,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    advanced: bool = False,
    port: int | None = None,
    plan: DeploymentPlan | None = None,
    assume_yes: bool = False,
    start: bool = False,
) -> DeploymentPlan | None:
    if plan is None:
        plan = gather_plan(
            input_fn=input_fn,
            secret_fn=secret_fn,
            output=output,
            project_root=project_root,
            home=home,
            advanced=advanced,
            port=port,
        )
    output(plan_summary(plan))
    if not assume_yes and not _yes_no(input_fn, t("prompt.setup_gate"), False):
        output(t("msg.cancelled"))
        return None
    if dry_run:
        output(t("msg.dry_run"))
        return plan
    runner = runner or CommandRunner()
    shared_lock: SessionLockProtocol = session_lock or UserWizardLock(plan)
    docker_lock: SessionLockProtocol | None = None
    if plan.target in {"compose", "docker"}:
        docker_lock = DockerDaemonLock(runner, plan.image)
    try:
        if plan.target == "native" and hasattr(os, "geteuid") and os.geteuid() == 0:
            raise DeployError("native deployment must not be run as root")
        shared_lock.acquire()
        setup_plan(
            plan,
            runner=runner,
            force=force,
            listener_checker=listener_checker,
            docker_lock=docker_lock,
        )
        output(t("msg.setup_done"))
        output(napcat_instructions(plan))
        if not start and not _yes_no(input_fn, t("prompt.start_gate"), False):
            output(t("msg.not_started", command=start_command(plan)))
            output(manage_commands(plan))
            return plan
        start_plan(plan, runner=runner, listener_checker=listener_checker, output=output)
        output(t("msg.started"))
        output(manage_commands(plan))
        return plan
    finally:
        if docker_lock is not None:
            docker_lock.release()
        shared_lock.release()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Pretender deployment wizard")
    parser.add_argument("--dry-run", action="store_true", help="plan only; do not write or start")
    parser.add_argument("--force", action="store_true", help="replace wizard-owned files after backing them up")
    parser.add_argument(
        "--lang", choices=("auto", "zh", "en"), default="auto",
        help="wizard language (default: detected from the locale)",
    )
    parser.add_argument(
        "--advanced", action="store_true",
        help="ask every question instead of defaulting the optional ones",
    )
    parser.add_argument(
        "--port", default=None,
        help=f"OneBot reverse WebSocket port (default: first free port from {DEFAULT_PORT})",
    )
    parser.add_argument(
        "--non-interactive", action="store_true",
        help="build the plan from flags and environment variables; ask nothing",
    )
    parser.add_argument("--target", choices=("compose", "docker", "native"), default="compose")
    parser.add_argument("--provider", choices=("deepseek", "openai", "custom"), default="deepseek")
    parser.add_argument("--base-url", default=None, help="OpenAI-compatible base URL")
    parser.add_argument("--model", default=None, help="planner model ID")
    parser.add_argument("--reply-model", default=None, help="reply model ID (default: --model)")
    parser.add_argument("--image", default=DEFAULT_IMAGE, help="container image for Docker targets")
    parser.add_argument("--native-service", choices=("foreground", "systemd"), default="foreground")
    parser.add_argument(
        "--api-key-env", default=LLM_ENV,
        help=f"environment variable holding the LLM API key (default: {LLM_ENV})",
    )
    parser.add_argument(
        "--token-env", default=ONEBOT_ENV,
        help=f"environment variable holding the OneBot token (default: {ONEBOT_ENV}; generated when unset)",
    )
    parser.add_argument(
        "--yes", action="store_true",
        help="skip the setup confirmation (the live-start gate still applies unless --start)",
    )
    parser.add_argument(
        "--start", action="store_true",
        help="start the live process once setup succeeds; NapCat must already be configured",
    )
    args = parser.parse_args(argv)
    try:
        set_language(args.lang)
        port = validate_port(args.port) if args.port is not None else None
        plan = None
        if args.non_interactive:
            plan = plan_from_options(
                target=args.target,
                provider_kind=args.provider,
                base_url=args.base_url,
                planner_model=args.model,
                reply_model=args.reply_model,
                port=port,
                image=args.image,
                native_service=args.native_service,
                api_key_env=args.api_key_env,
                token_env=args.token_env,
            )
        run_wizard(
            dry_run=args.dry_run,
            force=args.force,
            advanced=args.advanced,
            port=port,
            plan=plan,
            assume_yes=args.yes or args.non_interactive,
            start=args.start,
        )
    except (KeyboardInterrupt, EOFError):
        print("", file=sys.stderr)
        print(t("msg.cancelled"), file=sys.stderr)
        return 130
    except (DeployError, OSError, subprocess.CalledProcessError) as exc:
        print(t("error.prefix", error=exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
