#!/usr/bin/env python3
"""Small, deliberately boring, one-click deployment wizard.

The wizard only uses the Python standard library.  In particular, commands are
always passed to ``subprocess`` as argument arrays: no shell is involved.
"""

from __future__ import annotations

import argparse
import getpass
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import tomllib
from dataclasses import dataclass
from typing import Any, Callable, Mapping, Protocol, Sequence
from urllib.parse import urlsplit

try:
    import fcntl
except ImportError:  # pragma: no cover - native locking is Linux-oriented
    fcntl = None  # type: ignore[assignment]


DEFAULT_IMAGE = "ghcr.io/redstonexs/pretender:v1.0.2"
LLM_ENV = "PRETENDER_LLM_API_KEY"
ONEBOT_ENV = "ONEBOT_ACCESS_TOKEN"
WIZARD_MARKER = "Generated by the Pretender deployment wizard."
_MODEL_MAX = 200
_ENV_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SECRET_CHARS = re.compile(r"^[A-Za-z0-9._\-/+=:@%]+$")
WIZARD_LOCK_CONTAINER = "pretender-wizard-lock"
WIZARD_LOCK_LABEL = "io.pretender.wizard-lock=true"


class DeployError(RuntimeError):
    """An expected, user-actionable deployment error."""


@dataclass(frozen=True)
class Provider:
    base_url: str
    planner_model: str
    reply_model: str
    api_key: str
    http_loopback_confirmed: bool = False


@dataclass(frozen=True)
class Features:
    splitting: bool = True
    typo: bool = True
    media_enabled: bool = False


@dataclass(frozen=True)
class DeploymentPlan:
    target: str
    provider: Provider
    features: Features
    onebot_token: str
    project_root: Path
    config_path: Path
    environment_path: Path
    storage_path: str
    image: str = DEFAULT_IMAGE
    native_service: str = "foreground"
    home: Path = Path.home()

    @property
    def venv_path(self) -> Path:
        return self.home / ".local" / "share" / "pretender" / "venv"

    @property
    def unit_path(self) -> Path:
        return self.home / ".config" / "systemd" / "user" / "pretender.service"

    @property
    def venv_marker_path(self) -> Path:
        return self.venv_path.parent / "venv.wizard.marker"

    @property
    def shared_state_dir(self) -> Path:
        return self.home / ".local" / "state" / "pretender"

    @property
    def shared_lock_path(self) -> Path:
        return self.shared_state_dir / ".wizard.lock"


class RunnerProtocol(Protocol):
    def run(
        self,
        argv: Sequence[str],
        *,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        check: bool = True,
        capture_output: bool = False,
    ) -> Any:
        ...


def _text(value: str, label: str) -> str:
    if not isinstance(value, str) or any(
        ord(char) < 32 or ord(char) == 127 for char in value
    ):
        raise DeployError(f"{label} contains control characters")
    return value


def trusted_project_root() -> Path:
    """Return this checkout's root, never the caller's current directory."""

    root = Path(__file__).resolve().parents[1]
    manifest = root / "pyproject.toml"
    try:
        with manifest.open("rb") as stream:
            project = tomllib.load(stream).get("project", {})
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise DeployError(f"trusted project root is invalid: {manifest}") from exc
    if not isinstance(project, dict) or project.get("name") != "pretender":
        raise DeployError(f"trusted project root is not Pretender: {root}")
    return root


def validate_model_id(value: str) -> str:
    raw = _text(value, "model ID")
    value = raw.strip()
    if not value:
        raise DeployError("model ID must not be empty")
    if raw != value or not value.isprintable():
        raise DeployError("model ID must be nonempty and printable")
    if len(value) > _MODEL_MAX:
        raise DeployError(f"model ID is too long (maximum {_MODEL_MAX} characters)")
    return value


def _is_loopback(host: str | None) -> bool:
    if not host:
        return False
    if host.lower().rstrip(".") == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def validate_base_url(value: str, *, allow_http_loopback: bool = False) -> str:
    value = _text(value, "base URL").strip()
    if any(char.isspace() for char in value):
        raise DeployError("base URL must not contain whitespace")
    try:
        parsed = urlsplit(value)
        host = parsed.hostname
    except ValueError as exc:
        raise DeployError("base URL is malformed") from exc
    if parsed.scheme not in ("http", "https") or not parsed.netloc or not host:
        raise DeployError("base URL must be an absolute http or https URL")
    if parsed.username is not None or parsed.password is not None:
        raise DeployError("base URL must not contain credentials")
    try:
        parsed.port
    except ValueError as exc:
        raise DeployError("base URL has an invalid port") from exc
    if parsed.query or parsed.fragment:
        raise DeployError("base URL must not contain a query or fragment")
    if parsed.scheme == "http" and not (
        allow_http_loopback and _is_loopback(host)
    ):
        raise DeployError("plain http is permitted only for an explicitly confirmed loopback endpoint")
    return value


def validate_secret(value: str, label: str) -> str:
    """Validate the deliberately small raw ``KEY=value`` secret alphabet."""

    value = _text(value, label)
    if not value or not _SECRET_CHARS.fullmatch(value):
        raise DeployError(
            f"{label} must be nonempty and contain only Docker/systemd-safe "
            "characters (letters, numbers, . _ - / + = : @ %)"
        )
    return value


def toml_string(value: str, label: str = "value") -> str:
    """Return a safe TOML basic string, rejecting rather than hiding controls."""

    _text(value, label)
    return json.dumps(value, ensure_ascii=False)


def render_config(
    provider: Provider, features: Features, storage_path: str
) -> str:
    """Render the minimal config; secrets are represented by one fixed ref."""

    base_url = validate_base_url(
        provider.base_url, allow_http_loopback=provider.http_loopback_confirmed
    )
    planner = validate_model_id(provider.planner_model)
    reply = validate_model_id(provider.reply_model)
    validate_secret(provider.api_key, "API key")
    _text(storage_path, "storage path")
    pipeline = ["sanitize"]
    if features.splitting:
        pipeline.append("split")
    if features.typo:
        pipeline.append("typo")
    pipeline_toml = "[" + ", ".join(toml_string(item) for item in pipeline) + "]"
    max_split = 3 if features.splitting else 1
    typo_rate = 0.03 if features.typo else 0.0
    return "\n".join(
        [
            f"# {WIZARD_MARKER}",
            "",
            "[llm.profiles.planner]",
            f"base_url = {toml_string(base_url, 'base URL')}",
            f"api_key = \"${{{LLM_ENV}}}\"",
            f"model = {toml_string(planner, 'planner model')}",
            "",
            "[llm.profiles.reply]",
            f"base_url = {toml_string(base_url, 'base URL')}",
            f"api_key = \"${{{LLM_ENV}}}\"",
            f"model = {toml_string(reply, 'reply model')}",
            "",
            "[output]",
            f"pipeline = {pipeline_toml}",
            f"max_split = {max_split}",
            f"typo_rate = {typo_rate}",
            "",
            "[media]",
            f"enabled = {str(features.media_enabled).lower()}",
            "",
            "[adapter]",
            'name = "onebot"',
            "",
            "[adapter.onebot]",
            'mode = "reverse_ws"',
            'host = "127.0.0.1"',
            "port = 3001",
            'path = "/onebot/v11/ws"',
            f'access_token = "${{{ONEBOT_ENV}}}"',
            "",
            "[storage]",
            f"db_path = {toml_string(storage_path, 'storage path')}",
            "",
        ]
    )


def _dotenv_value(value: str, label: str) -> str:
    value = validate_secret(value, label)
    if "\n" in value or "\r" in value or "\x00" in value:
        raise DeployError(f"{label} contains a newline or NUL")
    return value


def render_docker_environment(plan: DeploymentPlan) -> str:
    """Render the project .env without exposing it in wizard output.

    The generated config and environment use one generic LLM key name for all
    provider presets.
    """

    image = _dotenv_value(plan.image, "image")
    key = _dotenv_value(plan.provider.api_key, "LLM secret")
    token = _dotenv_value(plan.onebot_token, "OneBot secret")
    lines = [
        f"# {WIZARD_MARKER}",
        f"PRETENDER_IMAGE={image}",
        f"{LLM_ENV}={key}",
        f"{ONEBOT_ENV}={token}",
        "",
    ]
    return "\n".join(lines)


def render_systemd_environment(plan: DeploymentPlan) -> str:
    """Serialize environment values using systemd EnvironmentFile quoting."""

    values = {LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token}
    lines = [f"# {WIZARD_MARKER}"]
    for key, value in values.items():
        if not _ENV_KEY.fullmatch(key):
            raise DeployError(f"invalid environment variable name {key!r}")
        value = validate_secret(value, f"{key} secret")
        if "\n" in value or "\r" in value or "\x00" in value:
            raise DeployError(f"{key} contains a newline or NUL")
        lines.append(f"{key}={escape_systemd_value(value)}")
    lines.append("")
    return "\n".join(lines)


def escape_systemd_value(value: str) -> str:
    """Escape a systemd EnvironmentFile value; newline and NUL are forbidden."""

    if not isinstance(value, str):
        raise DeployError("systemd environment value must be a string")
    if "\n" in value or "\r" in value or "\x00" in value:
        raise DeployError("systemd environment values must not contain newline or NUL")
    _text(value, "systemd environment value")
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
    )


def render_systemd_unit(plan: DeploymentPlan) -> str:
    if plan.native_service != "systemd":
        raise DeployError("systemd unit requested for a foreground plan")
    executable = _safe_systemd_path(plan.venv_path / "bin" / "pretender")
    config = _safe_systemd_path(plan.config_path)
    environment = _safe_systemd_path(plan.environment_path)
    return "\n".join(
        [
            f"# {WIZARD_MARKER}",
            "[Unit]",
            "Description=Pretender live bot",
            "After=network-online.target",
            "StartLimitIntervalSec=60",
            "StartLimitBurst=3",
            "",
            "[Service]",
            "Type=simple",
            f"ExecStart={executable} run --live --config {config}",
            f"EnvironmentFile={environment}",
            "Restart=on-failure",
            "RestartSec=10",
            "TimeoutStopSec=30",
            "UMask=0077",
            "NoNewPrivileges=true",
            "PrivateTmp=true",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )


def build_plan(
    target: str,
    provider: Provider,
    features: Features,
    onebot_token: str,
    *,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    image: str = DEFAULT_IMAGE,
    native_service: str = "foreground",
) -> DeploymentPlan:
    if target not in {"compose", "docker", "native"}:
        raise DeployError("target must be compose, docker, or native")
    if native_service not in {"foreground", "systemd"}:
        raise DeployError("native service must be foreground or systemd")
    if target != "native":
        native_service = "foreground"
    provider = Provider(
        validate_base_url(
            provider.base_url, allow_http_loopback=provider.http_loopback_confirmed
        ),
        validate_model_id(provider.planner_model),
        validate_model_id(provider.reply_model),
        validate_secret(provider.api_key, "API key"),
        provider.http_loopback_confirmed,
    )
    token = validate_secret(onebot_token, "OneBot token")
    root = trusted_project_root() if project_root is None else Path(project_root)
    root = root.resolve()
    home_path = Path.home() if home is None else Path(home).resolve()
    if target == "native":
        config = home_path / ".config" / "pretender" / "config.toml"
        env = home_path / ".config" / "pretender" / "environment"
        storage = str(home_path / ".local" / "state" / "pretender" / "pretender.db")
    else:
        config = root / "config" / "config.toml"
        env = root / ".env"
        storage = "data/pretender.db"
    image = _text(image, "image").strip()
    if not image:
        raise DeployError("image must not be empty")
    if target in {"compose", "docker"}:
        validate_secret(image, "image")
    return DeploymentPlan(
        target=target,
        provider=provider,
        features=features,
        onebot_token=token,
        project_root=root,
        config_path=config,
        environment_path=env,
        storage_path=storage,
        image=image,
        native_service=native_service,
        home=home_path,
    )


def docker_compose_commands(plan: DeploymentPlan) -> list[list[str]]:
    if plan.target != "compose":
        raise DeployError("Compose commands requested for another target")
    compose = [
        "docker", "compose", "-f", str(plan.project_root / "docker-compose.yml"),
        "--project-directory", str(plan.project_root),
    ]
    return [
        ["docker", "info"],
        ["docker", "volume", "create", "pretender-data"],
        compose + ["config", "--quiet"],
        compose + ["pull"],
        compose + ["run", "--rm", "--no-deps", "pretender", "init", "--config", "/config/config.toml"],
        compose + ["up", "-d"],
    ]


def docker_run_commands(plan: DeploymentPlan) -> list[list[str]]:
    if plan.target != "docker":
        raise DeployError("docker run commands requested for another target")
    config_mount = f"type=bind,src={plan.config_path.resolve()},dst=/config/config.toml,readonly"
    data_mount = "type=volume,src=pretender-data,dst=/config/data"
    init = [
        "docker", "run", "--rm", "--network", "host", "--env-file",
        str(plan.environment_path.resolve()), "--mount", config_mount,
        "--mount", data_mount, plan.image,
        "init", "--config", "/config/config.toml",
    ]
    return [
        ["docker", "info"],
        ["docker", "volume", "create", "pretender-data"],
        ["docker", "pull", plan.image],
        ["docker", "container", "inspect", "pretender"],
        init,
        [
            "docker",
            "run",
            "--name",
            "pretender",
            "--detach",
            "--network",
            "host",
            "--restart",
            "unless-stopped",
            "--label",
            "io.pretender.wizard-managed=true",
            "--env-file",
            str(plan.environment_path.resolve()),
            "--mount",
            config_mount,
            "--mount",
            data_mount,
            plan.image,
            "run",
            "--live",
            "--config",
            "/config/config.toml",
        ],
    ]


def docker_run_init_command(plan: DeploymentPlan) -> list[str]:
    if plan.target != "docker":
        raise DeployError("docker run init requested for another target")
    config_mount = f"type=bind,src={plan.config_path.resolve()},dst=/config/config.toml,readonly"
    data_mount = "type=volume,src=pretender-data,dst=/config/data"
    return [
        "docker", "run", "--rm", "--network", "host", "--env-file",
        str(plan.environment_path.resolve()), "--mount", config_mount,
        "--mount", data_mount, plan.image,
        "init", "--config", "/config/config.toml",
    ]


def native_init_command(plan: DeploymentPlan, venv_path: Path | None = None) -> list[str]:
    executable_root = venv_path or plan.venv_path
    return [
        str(executable_root / "bin" / "pretender"),
        "init",
        "--config",
        str(plan.config_path.resolve()),
    ]


class CommandRunner:
    def run(
        self,
        argv: Sequence[str],
        *,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
        check: bool = True,
        capture_output: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            list(argv),
            cwd=str(cwd) if cwd is not None else None,
            env=dict(env) if env is not None else None,
            check=check,
            capture_output=capture_output,
            text=True,
        )


def _run(
    runner: RunnerProtocol,
    argv: Sequence[str],
    *,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
    check: bool = True,
    capture_output: bool = False,
) -> subprocess.CompletedProcess[str]:
    return runner.run(argv, cwd=cwd, env=env, check=check, capture_output=capture_output)


def _wizard_owned(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8") as stream:
            return WIZARD_MARKER in stream.read(4096)
    except (OSError, UnicodeError):
        return False


def _backup_path(path: Path) -> Path:
    candidate = path.with_name(path.name + ".bak")
    index = 1
    while candidate.exists() or candidate.is_symlink():
        candidate = path.with_name(path.name + f".bak.{index}")
        index += 1
    return candidate


def atomic_write(path: str | Path, content: str, *, mode: int = 0o644, force: bool = False) -> None:
    """Atomically write one regular target, backing up only wizard files."""

    _commit_artifacts([(Path(path), content, mode)], force=force)


def _check_parent_components(path: Path, root: Path) -> None:
    """Reject symlinked components between a deployment root and a target."""

    root = root.absolute()
    parent = path.absolute().parent
    try:
        relative = parent.relative_to(root)
    except ValueError as exc:
        raise DeployError(f"deployment target escapes its root: {path}") from exc
    current = root
    for component in relative.parts:
        current /= component
        if current.is_symlink():
            raise DeployError(f"refusing symlinked parent component {current}")
        if current.exists() and not current.is_dir():
            raise DeployError(f"deployment parent is not a directory: {current}")


def _preflight_destination(path: Path, *, force: bool) -> None:
    for parent in path.parents:
        if parent.is_symlink():
            raise DeployError(f"refusing symlinked parent component {parent}")
    if path.is_symlink():
        raise DeployError(f"refusing symlink target {path}")
    if path.exists() and not path.is_file():
        raise DeployError(f"refusing non-regular target {path}")
    if path.exists():
        if not force:
            raise DeployError(f"refusing to overwrite {path}; use --force")
        if not _wizard_owned(path):
            raise DeployError(f"refusing to replace non-wizard file {path}")
        _backup_path(path)  # reserve/check the backup naming policy before writes


def _stage_artifacts(
    artifacts: Sequence[tuple[Path, str, int]], *, force: bool, root: Path | None = None
) -> list[tuple[Path, Path, bool, Path | None]]:
    paths = [path for path, _, _ in artifacts]
    if len(set(paths)) != len(paths):
        raise DeployError("duplicate deployment artifact destination")
    for path in paths:
        if root is not None:
            _check_parent_components(path, root)
        _preflight_destination(path, force=force)
    staged: list[tuple[Path, Path, bool, Path | None]] = []
    temporary_paths: list[Path] = []
    try:
        for destination, content, mode in artifacts:
            destination.parent.mkdir(parents=True, exist_ok=True)
            fd, temporary = tempfile.mkstemp(
                prefix=f".{destination.name}.", dir=destination.parent
            )
            temporary_path = Path(temporary)
            temporary_paths.append(temporary_path)
            os.fchmod(fd, mode)
            with os.fdopen(fd, "wb") as stream:
                stream.write(content.encode("utf-8"))
                stream.flush()
                os.fsync(stream.fileno())
            staged.append((destination, temporary_path, destination.exists(), None))
    except BaseException:
        for temporary in temporary_paths:
            try:
                temporary.unlink()
            except OSError:
                pass
        raise
    return staged


@dataclass
class _ArtifactRecord:
    destination: Path
    existed: bool
    backup: Path | None
    secret: bool = False


@dataclass
class _ArtifactReceipt:
    records: list[_ArtifactRecord]

    def rollback(self) -> None:
        failures: list[str] = []
        for record in reversed(self.records):
            try:
                if record.existed and record.backup is not None:
                    os.replace(record.backup, record.destination)
                elif record.destination.is_file() and not record.destination.is_symlink():
                    record.destination.unlink()
            except OSError as exc:
                failures.append(str(exc))
        if failures:
            raise DeployError(
                "artifact rollback failed; private backups were preserved: "
                + "; ".join(failures)
            )
        for record in self.records:
            if record.backup is not None and record.backup.exists():
                try:
                    record.backup.unlink()
                except OSError:
                    pass


def _private_secret_backup(path: Path, content: bytes, root: Path) -> Path:
    backup_dir = root / ".local" / "state" / "pretender" / "deploy-backups"
    _check_parent_components(backup_dir / "env", root)
    if backup_dir.is_symlink() or (backup_dir.exists() and not backup_dir.is_dir()):
        raise DeployError(f"refusing unsafe private backup directory {backup_dir}")
    backup_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(backup_dir, 0o700)
    fd, temporary = tempfile.mkstemp(prefix=".environment.", suffix=".backup", dir=backup_dir)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        try:
            os.close(fd)
        except OSError:
            pass
        try:
            Path(temporary).unlink()
        except OSError:
            pass
        raise
    return Path(temporary)


def _commit_artifacts(
    artifacts: Sequence[tuple[Path, str, int]], *, force: bool,
    root: Path | None = None, secret_paths: set[Path] | None = None,
    secret_backup_root: Path | None = None,
) -> _ArtifactReceipt:
    staged = _stage_artifacts(artifacts, force=force, root=root)
    committed: list[_ArtifactRecord] = []
    backups: list[Path] = []
    secret_paths = secret_paths or set()
    try:
        for destination, temporary, existed, _ in staged:
            backup = None
            if existed:
                if destination in secret_paths:
                    if secret_backup_root is None:
                        raise DeployError("private secret backup root is required")
                    backup = _private_secret_backup(
                        destination, destination.read_bytes(), secret_backup_root
                    )
                else:
                    backup = _backup_path(destination)
                    shutil.copy2(destination, backup)
                backups.append(backup)
            os.replace(temporary, destination)
            committed.append(_ArtifactRecord(destination, existed, backup, destination in secret_paths))
            os.chmod(destination, next(mode for path, _, mode in artifacts if path == destination))
    except BaseException:
        try:
            _ArtifactReceipt(committed).rollback()
        except DeployError:
            raise
        for backup in backups:
            if backup.exists():
                try:
                    backup.unlink()
                except OSError:
                    pass
        for destination, temporary, _, _ in staged:
            if temporary.exists():
                try:
                    temporary.unlink()
                except OSError:
                    pass
        raise
    finally:
        for _, temporary, _, _ in staged:
            if temporary.exists():
                try:
                    temporary.unlink()
                except OSError:
                    pass
    return _ArtifactReceipt(committed)


def _write_artifacts(plan: DeploymentPlan, *, force: bool) -> _ArtifactReceipt:
    artifacts: list[tuple[Path, str, int]] = [
        (plan.config_path, render_config(plan.provider, plan.features, plan.storage_path), 0o644),
    ]
    if plan.target == "native":
        artifacts.append((plan.environment_path, render_systemd_environment(plan), 0o600))
    else:
        artifacts.append((plan.environment_path, render_docker_environment(plan), 0o600))
    if plan.target == "native" and not plan.venv_path.exists():
        artifacts.append((plan.venv_marker_path, f"# {WIZARD_MARKER}\n", 0o600))
    if plan.target == "native" and plan.native_service == "systemd":
        artifacts.append((plan.unit_path, render_systemd_unit(plan), 0o600))
    root = plan.project_root if plan.target in {"compose", "docker"} else plan.home
    secret_paths = {plan.environment_path}
    return _commit_artifacts(
        artifacts,
        force=force,
        root=root,
        secret_paths=secret_paths,
        secret_backup_root=plan.home,
    )


def _ensure_venv(path: Path) -> None:
    if path.is_symlink():
        raise DeployError(f"refusing symlink virtual environment {path}")
    if path.exists() and not path.is_dir():
        raise DeployError(f"virtual environment target is not a directory: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)


def _ensure_private_config_dir(plan: DeploymentPlan) -> None:
    if plan.target != "native":
        return
    directory = plan.environment_path.parent
    _check_parent_components(directory / "environment", plan.home)
    if directory.is_symlink() or (directory.exists() and not directory.is_dir()):
        raise DeployError(f"native config directory is not a private directory: {directory}")
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    if directory.is_symlink():
        raise DeployError(f"refusing symlinked native config directory {directory}")
    os.chmod(directory, 0o700)


def _ensure_private_state_dir(plan: DeploymentPlan) -> Path:
    if plan.target != "native":
        raise DeployError("native state directory requested for a Docker plan")
    state_dir = Path(plan.storage_path).parent
    shared_state_dir = _ensure_private_user_state_dir(plan.home)
    if state_dir != shared_state_dir:
        raise DeployError("native state directory is not the shared deployment state root")
    _check_parent_components(state_dir / "pretender.db", plan.home)
    return state_dir


def _ensure_private_user_state_dir(home: Path) -> Path:
    state_dir = home / ".local" / "state" / "pretender"
    _check_parent_components(state_dir / ".wizard.lock", home)
    if state_dir.is_symlink() or (state_dir.exists() and not state_dir.is_dir()):
        raise DeployError(f"private deployment state directory is unsafe: {state_dir}")
    state_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    if state_dir.is_symlink():
        raise DeployError(f"refusing symlinked deployment state directory {state_dir}")
    os.chmod(state_dir, 0o700)
    return state_dir


def _secure_native_database(plan: DeploymentPlan) -> None:
    database = Path(plan.storage_path)
    for path in (database, Path(f"{database}-wal"), Path(f"{database}-shm")):
        if path.is_symlink():
            raise DeployError(f"refusing symlinked native database file {path}")
        if path.exists():
            if not path.is_file():
                raise DeployError(f"native database sidecar is not a regular file: {path}")
            os.chmod(path, 0o600)


def _run_with_umask(
    runner: RunnerProtocol,
    argv: Sequence[str],
    *,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> Any:
    old_umask = os.umask(0o077)
    try:
        return _run(runner, argv, cwd=cwd, env=env)
    finally:
        os.umask(old_umask)


def _cleanup_new_venv(plan: DeploymentPlan, *, existed: bool, marker_existed: bool) -> None:
    if existed or plan.venv_path.is_symlink():
        return
    marker = plan.venv_marker_path
    owned_marker = marker.is_file() and _wizard_owned(marker)
    if not owned_marker:
        return
    if plan.venv_path.is_dir() and not plan.venv_path.is_symlink():
        shutil.rmtree(plan.venv_path)
    if not marker_existed and marker.is_file() and _wizard_owned(marker):
        marker.unlink()


def _preflight_venv(plan: DeploymentPlan, *, force: bool) -> None:
    marker = plan.venv_marker_path
    if plan.venv_path.is_symlink():
        raise DeployError(f"refusing symlink virtual environment {plan.venv_path}")
    if plan.venv_path.exists() and not plan.venv_path.is_dir():
        raise DeployError(f"virtual environment target is not a directory: {plan.venv_path}")
    if marker.is_symlink():
        raise DeployError(f"refusing symlink virtual environment marker {marker}")
    if plan.venv_path.exists() and (
        not marker.is_file() or not _wizard_owned(marker)
    ):
        raise DeployError("existing virtual environment is not wizard-owned")
    if not plan.venv_path.exists() and marker.exists():
        _preflight_destination(marker, force=force)


def _safe_systemd_path(path: Path) -> str:
    value = str(path.resolve())
    if not value.startswith("/"):
        raise DeployError("systemd paths must be absolute")
    if any(char.isspace() or char in "'\"\\$`" for char in value):
        raise DeployError(f"systemd path contains unsupported characters: {value}")
    return value


def controlled_compose_env(plan: DeploymentPlan) -> dict[str, str]:
    """Inherit ordinary process settings but control every deployment secret."""

    environment = dict(os.environ)
    environment.update(
        {
            "PRETENDER_IMAGE": plan.image,
            LLM_ENV: plan.provider.api_key,
            ONEBOT_ENV: plan.onebot_token,
        }
    )
    return environment


def _compose_command(plan: DeploymentPlan, *args: str) -> list[str]:
    return [
        "docker",
        "compose",
        "-f",
        str(plan.project_root / "docker-compose.yml"),
        "--project-directory",
        str(plan.project_root),
        *args,
    ]


def check_listener(
    host: str = "127.0.0.1", port: int = 3001, *, timeout: float = 0.25
) -> None:
    """Fail clearly when the reverse-WebSocket listener port is occupied."""

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.settimeout(timeout)
        sock.bind((host, port))
    except OSError as exc:
        raise DeployError(f"{host}:{port} is already in use; refusing to start") from exc
    finally:
        sock.close()


def _preflight_destinations(plan: DeploymentPlan, *, force: bool) -> None:
    root = plan.project_root if plan.target in {"compose", "docker"} else plan.home
    paths = [plan.config_path, plan.environment_path]
    if plan.target == "native":
        if not plan.venv_path.exists():
            paths.append(plan.venv_marker_path)
        if plan.native_service == "systemd":
            paths.append(plan.unit_path)
    for path in paths:
        _check_parent_components(path, root)
        _preflight_destination(path, force=force)
    if plan.target == "native":
        _check_parent_components(Path(plan.storage_path), plan.home)
        _preflight_venv(plan, force=force)


def _preflight_systemd(runner: RunnerProtocol) -> None:
    active = _run(
        runner,
        ["systemctl", "--user", "is-active", "--quiet", "pretender.service"],
        check=False,
    )
    if active.returncode == 0:
        raise DeployError("pretender.service is already active; refusing to replace it")
    enabled = _run(
        runner,
        ["systemctl", "--user", "is-enabled", "--quiet", "pretender.service"],
        check=False,
    )
    if enabled.returncode == 0:
        raise DeployError("pretender.service is already enabled; refusing to replace it")


def _wait_systemd_active(
    runner: RunnerProtocol, *, attempts: int = 3, delay: float = 0.05
) -> None:
    for attempt in range(attempts):
        active = _run(
            runner,
            ["systemctl", "--user", "is-active", "--quiet", "pretender.service"],
            check=False,
        )
        if active.returncode == 0:
            return
        if attempt + 1 < attempts:
            time.sleep(delay)
    raise DeployError("pretender.service did not become active after start")


def _preflight_docker(
    plan: DeploymentPlan,
    runner: RunnerProtocol,
    *,
    listener_checker: Callable[[], None],
) -> None:
    _run(runner, ["docker", "info"])
    running = _run(
        runner,
        ["docker", "ps", "--filter", "volume=pretender-data", "--format", "{{.Names}}"],
        capture_output=True,
    )
    if running.stdout.strip():
        raise DeployError("a running container already uses pretender-data; refusing to start")
    existing = _run(
        runner,
        ["docker", "container", "inspect", "pretender"],
        check=False,
        capture_output=True,
    )
    if existing.returncode == 0:
        raise DeployError("container named 'pretender' already exists; refusing to replace it")
    listener_checker()


class DockerDaemonLock:
    """A stopped, daemon-owned lock container held for one wizard session."""

    def __init__(self, runner: RunnerProtocol, image: str):
        self.runner = runner
        self.image = image
        self.acquired = False

    def acquire(self) -> None:
        if self.acquired:
            return
        _run(
            self.runner,
            [
                "docker", "create", "--name", WIZARD_LOCK_CONTAINER,
                "--label", WIZARD_LOCK_LABEL, "--entrypoint", "/bin/true",
                self.image,
            ],
        )
        self.acquired = True

    def release(self) -> None:
        if not self.acquired:
            return
        try:
            _run(self.runner, ["docker", "rm", WIZARD_LOCK_CONTAINER])
        finally:
            self.acquired = False


class SessionLockProtocol(Protocol):
    def acquire(self) -> None:
        ...

    def release(self) -> None:
        ...


class UserWizardLock:
    """A shared non-blocking lock for every kind of wizard session."""

    def __init__(self, plan: DeploymentPlan):
        self.plan = plan
        self.handle: Any | None = None

    def acquire(self) -> None:
        if self.handle is not None:
            return
        if fcntl is None:
            raise DeployError("native wizard locking is unavailable on this platform")
        state_dir = _ensure_private_user_state_dir(self.plan.home)
        path = self.plan.shared_lock_path
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise DeployError(f"refusing unsafe native wizard lock {path}")
        flags = os.O_CREAT | os.O_RDWR
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd: int | None = None
        try:
            fd = os.open(path, flags, 0o600)
            os.chmod(path, 0o600)
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except (BlockingIOError, OSError) as exc:
            if fd is not None:
                os.close(fd)
            if isinstance(exc, BlockingIOError) or getattr(exc, "errno", None) in {11, 13}:
                raise DeployError("another native deployment wizard is already running") from exc
            raise DeployError(f"cannot acquire native wizard lock: {path}") from exc
        self.handle = fd

    def release(self) -> None:
        if self.handle is None:
            return
        fd = self.handle
        self.handle = None
        try:
            assert fcntl is not None
            fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)


# Kept as a source-compatible name for callers of the earlier native-only API.
NativeWizardLock = UserWizardLock


def _new_venv_staging_path(plan: DeploymentPlan) -> Path:
    parent = plan.venv_path.parent
    _check_parent_components(plan.venv_path, plan.home)
    if parent.is_symlink() or (parent.exists() and not parent.is_dir()):
        raise DeployError(f"unsafe native venv parent {parent}")
    parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(parent, 0o700)
    return Path(tempfile.mkdtemp(prefix=".venv-staging-", dir=parent))


def _remove_staging_venv(path: Path | None) -> None:
    if path is not None and path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)


def promote_venv(plan: DeploymentPlan, staging: Path) -> None:
    """Atomically promote a completed venv, preserving an old one on failure."""

    final = plan.venv_path
    if staging.is_symlink() or not staging.is_dir():
        raise DeployError("venv staging path is not a regular directory")
    previous: Path | None = None
    if final.exists() or final.is_symlink():
        if final.is_symlink() or not final.is_dir():
            raise DeployError(f"unsafe native venv target {final}")
        if not plan.venv_marker_path.is_file() or not _wizard_owned(plan.venv_marker_path):
            raise DeployError("existing virtual environment is not wizard-owned")
        previous = final.with_name(f".venv-previous-{os.getpid()}")
        suffix = 1
        while previous.exists() or previous.is_symlink():
            previous = final.with_name(f".venv-previous-{os.getpid()}-{suffix}")
            suffix += 1
        os.replace(final, previous)
    try:
        os.replace(staging, final)
    except BaseException as exc:
        if previous is not None:
            try:
                os.replace(previous, final)
            except OSError as restore_error:
                raise DeployError("venv swap failed and the old venv could not be restored") from restore_error
        raise exc


def setup_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    force: bool = False,
    listener_checker: Callable[[], None] | None = None,
    docker_lock: SessionLockProtocol | None = None,
) -> DeploymentPlan:
    """Preflight and install artifacts, but never start a live process."""

    runner = runner or CommandRunner()
    listener_checker = listener_checker or check_listener
    _preflight_destinations(plan, force=force)
    if plan.target in {"compose", "docker"}:
        _preflight_docker(plan, runner, listener_checker=listener_checker)
    else:
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            raise DeployError("native deployment must not be run as root")
        if plan.native_service == "systemd":
            _preflight_systemd(runner)
        listener_checker()
    own_docker_lock = False
    staging_venv: Path | None = None
    receipt: _ArtifactReceipt | None = None
    try:
        if plan.target in {"compose", "docker"}:
            if plan.target == "compose":
                pre_env = controlled_compose_env(plan)
                _run(runner, _compose_command(plan, "pull"), cwd=plan.project_root, env=pre_env)
            else:
                _run(runner, ["docker", "pull", plan.image])
            if docker_lock is None:
                docker_lock = DockerDaemonLock(runner, plan.image)
                own_docker_lock = True
            docker_lock.acquire()
        if plan.target == "native":
            _ensure_private_state_dir(plan)
        _ensure_private_config_dir(plan)
        receipt = _write_artifacts(plan, force=force)
        if plan.target in {"compose", "docker"}:
            _run(runner, ["docker", "volume", "create", "pretender-data"])
            if plan.target == "compose":
                env = controlled_compose_env(plan)
                _run(
                    runner,
                    _compose_command(plan, "config", "--quiet"),
                    cwd=plan.project_root,
                    env=env,
                )
                _run(
                    runner,
                    _compose_command(
                        plan, "run", "--rm", "--no-deps", "pretender", "init",
                        "--config", "/config/config.toml",
                    ),
                    cwd=plan.project_root,
                    env=env,
                )
            else:
                _run(runner, docker_run_init_command(plan), cwd=plan.project_root)
        else:
            staging_venv = _new_venv_staging_path(plan)
            staging_python = staging_venv / "bin" / "python"
            _run(runner, [sys.executable, "-m", "venv", str(staging_venv)])
            _run(runner, [str(staging_python), "-m", "pip", "install", str(plan.project_root)])
            native_env = {**os.environ, LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token}
            _run_with_umask(
                runner, native_init_command(plan, staging_venv),
                cwd=plan.project_root, env=native_env,
            )
            _secure_native_database(plan)
            promote_venv(plan, staging_venv)
            staging_venv = None
    except BaseException:
        _remove_staging_venv(staging_venv)
        if receipt is not None:
            receipt.rollback()
        raise
    finally:
        if own_docker_lock and docker_lock is not None:
            docker_lock.release()
    return plan


def start_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    listener_checker: Callable[[], None] | None = None,
    output: Callable[[str], None] = print,
) -> None:
    """Run only after the caller has obtained the second confirmation."""

    runner = runner or CommandRunner()
    listener_checker = listener_checker or check_listener
    if plan.target in {"compose", "docker"}:
        _preflight_docker(plan, runner, listener_checker=listener_checker)
        if plan.target == "compose":
            _run(
                runner,
                _compose_command(plan, "up", "-d"),
                cwd=plan.project_root,
                env=controlled_compose_env(plan),
            )
        else:
            _run(runner, docker_run_commands(plan)[-1], cwd=plan.project_root)
        return
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        raise DeployError("native deployment must not be run as root")
    listener_checker()
    if plan.native_service == "systemd":
        _preflight_systemd(runner)
        _run(runner, ["systemctl", "--user", "daemon-reload"])
        _run(runner, ["systemctl", "--user", "enable", "pretender.service"])
        try:
            _run(runner, ["systemctl", "--user", "start", "pretender.service"])
            _wait_systemd_active(runner)
        except BaseException as start_error:
            try:
                _run(runner, ["systemctl", "--user", "disable", "pretender.service"])
            except BaseException as cleanup_error:
                raise DeployError(
                    "systemd start failed and disabling the service also failed"
                ) from cleanup_error
            raise start_error
        output("Systemd user service enabled; linger was not enabled automatically.")
        return
    environment = dict(os.environ)
    environment.update({LLM_ENV: plan.provider.api_key, ONEBOT_ENV: plan.onebot_token})
    _run_with_umask(
        runner,
        [
            str(plan.venv_path / "bin" / "pretender"),
            "run",
            "--live",
            "--config",
            str(plan.config_path.resolve()),
        ],
        cwd=plan.project_root,
        env=environment,
    )


def apply_plan(
    plan: DeploymentPlan,
    *,
    runner: RunnerProtocol | None = None,
    force: bool = False,
    output: Callable[[str], None] = print,
) -> None:
    """Set up artifacts and dependencies without starting a live process."""

    runner = runner or CommandRunner()
    setup_plan(plan, runner=runner, force=force)


def plan_summary(plan: DeploymentPlan) -> str:
    lines = [
        "Deployment plan (secrets redacted):",
        f"  target: {plan.target}",
        f"  provider: {plan.provider.base_url}",
        f"  planner model: {plan.provider.planner_model}",
        f"  reply model: {plan.provider.reply_model}",
        "  API key: <redacted>",
        "  OneBot token: <redacted>",
        f"  features: splitting={plan.features.splitting}, typo={plan.features.typo}, "
        f"media={plan.features.media_enabled}",
        f"  config: {plan.config_path.resolve()}",
        f"  storage: {plan.storage_path}",
    ]
    if plan.target in {"compose", "docker"}:
        lines.append(f"  image: {plan.image}")
    else:
        lines.append(f"  service: {plan.native_service}")
    return "\n".join(lines)


Input = Callable[[str], str]


def _ask(input_fn: Input, prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    answer = input_fn(f"{prompt}{suffix}: ").strip()
    return default if answer == "" and default is not None else answer


def _yes_no(input_fn: Input, prompt: str, default: bool) -> bool:
    default_text = "Y/n" if default else "y/N"
    while True:
        answer = input_fn(f"{prompt} [{default_text}]: ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False


def _choice(
    input_fn: Input,
    prompt: str,
    choices: Mapping[str, str],
    default: str | None = None,
) -> str:
    while True:
        suffix = f"; default {default}" if default is not None else ""
        answer = input_fn(f"{prompt} ({'/'.join(choices)}{suffix}): ").strip().lower()
        if not answer and default is not None:
            answer = default
        if answer in choices:
            return choices[answer]


def gather_plan(
    *,
    input_fn: Input = input,
    secret_fn: Input = getpass.getpass,
    output: Callable[[str], None] = print,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
) -> DeploymentPlan:
    target = _choice(
        input_fn,
        "Deployment target: 1) Docker Compose, 2) docker run, 3) native host",
        {"1": "compose", "2": "docker", "3": "native"},
    )
    native_service = "foreground"
    if target == "native":
        native_service = _choice(
            input_fn,
            "Native mode: foreground (default) or systemd user-service",
            {"f": "foreground", "foreground": "foreground", "s": "systemd", "systemd": "systemd"},
            default="f",
        )
    provider_kind = _choice(
        input_fn,
        "Provider: 1) DeepSeek, 2) OpenAI, 3) custom OpenAI-compatible",
        {"1": "deepseek", "2": "openai", "3": "custom"},
    )
    if provider_kind == "deepseek":
        base_url = "https://api.deepseek.com/v1"
        model_default = "deepseek-chat"
    elif provider_kind == "openai":
        base_url = "https://api.openai.com/v1"
        model_default = None
    else:
        base_url = _ask(input_fn, "OpenAI-compatible base URL")
        model_default = None
    http_loopback_confirmed = False
    try:
        validate_base_url(base_url)
    except DeployError:
        parts = urlsplit(base_url)
        if parts.scheme == "http" and _is_loopback(parts.hostname):
            if not _yes_no(input_fn, "This is plain HTTP on loopback; explicitly allow it", False):
                raise DeployError("plain HTTP loopback endpoint was not confirmed")
            validate_base_url(base_url, allow_http_loopback=True)
            http_loopback_confirmed = True
        else:
            raise
    planner_model = _ask(input_fn, "Planner model", model_default)
    validate_model_id(planner_model)
    reply_model = _ask(input_fn, "Reply model (blank uses planner)", planner_model)
    if reply_model == "":
        reply_model = planner_model
    validate_model_id(reply_model)
    api_key = validate_secret(secret_fn("API key (input hidden): "), "API key")
    supplied_token = secret_fn("OneBot token (blank generates one; input hidden): ")
    token = validate_secret(supplied_token, "OneBot token") if supplied_token.strip() else secrets.token_hex(32)
    splitting = _yes_no(input_fn, "Enable message splitting", True)
    typo = _yes_no(input_fn, "Enable typo simulation", True)
    media = _yes_no(input_fn, "Enable media catalog", False)
    image = DEFAULT_IMAGE
    if target in {"compose", "docker"}:
        image = _ask(input_fn, "Container image", DEFAULT_IMAGE)
    return build_plan(
        target,
        Provider(base_url, planner_model, reply_model, api_key, http_loopback_confirmed),
        Features(splitting, typo, media),
        token,
        project_root=project_root,
        home=home,
        image=image,
        native_service=native_service,
    )


def run_wizard(
    *,
    dry_run: bool = False,
    force: bool = False,
    input_fn: Input = input,
    secret_fn: Input = getpass.getpass,
    output: Callable[[str], None] = print,
    runner: RunnerProtocol | None = None,
    listener_checker: Callable[[], None] | None = None,
    session_lock: SessionLockProtocol | None = None,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
) -> DeploymentPlan | None:
    plan = gather_plan(
        input_fn=input_fn,
        secret_fn=secret_fn,
        output=output,
        project_root=project_root,
        home=home,
    )
    output(plan_summary(plan))
    if not _yes_no(input_fn, "Set up this plan now (no live process yet)", False):
        output("Cancelled.")
        return None
    if dry_run:
        output("Dry run: no files were written and no commands were run.")
        return plan
    runner = runner or CommandRunner()
    shared_lock: SessionLockProtocol = session_lock or UserWizardLock(plan)
    docker_lock: SessionLockProtocol | None = None
    if plan.target in {"compose", "docker"}:
        docker_lock = DockerDaemonLock(runner, plan.image)
    try:
        if plan.target == "native" and hasattr(os, "geteuid") and os.geteuid() == 0:
            raise DeployError("native deployment must not be run as root")
        shared_lock.acquire()
        setup_plan(
            plan,
            runner=runner,
            force=force,
            listener_checker=listener_checker,
            docker_lock=docker_lock,
        )
        output(
            "Setup complete. Securely open the protected environment file to configure "
            "the generated OneBot token in NapCat."
        )
        if not _yes_no(input_fn, "Start the live process now", False):
            output("Setup complete; live process was not started.")
            return plan
        start_plan(plan, runner=runner, listener_checker=listener_checker, output=output)
        return plan
    finally:
        if docker_lock is not None:
            docker_lock.release()
        shared_lock.release()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Pretender deployment wizard")
    parser.add_argument("--dry-run", action="store_true", help="plan only; do not write or start")
    parser.add_argument("--force", action="store_true", help="replace wizard-owned files after backing them up")
    args = parser.parse_args(argv)
    try:
        run_wizard(dry_run=args.dry_run, force=args.force)
    except (DeployError, OSError, subprocess.CalledProcessError) as exc:
        print(f"Deployment failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
